import {validateBezier} from '../authoring/easing.js';
import {easing,easeNames} from '../fx/math.js';
export const CONSTRAINT_TYPES=['translation','rotation','scale','transform','distance','ik','followPath'];
export const CONSTRAINT_COMMANDS=['constraint.add','constraint.update','constraint.remove','constraint.order','constraint.key'];
export const constraintChannels=(type)=>type==='transform'?['position','rotation','scale']:type==='translation'?['position']:['distance','ik','followPath'].includes(type)?[]:[type];
export const channelSize=(channel,dimension)=>channel==='rotation'&&dimension===2?1:dimension;
const fail=message=>{throw Error('Constraints: '+message);},finite=(v,a=-1e6,b=1e6)=>Number.isFinite(v)&&v>=a&&v<=b;
export function constraintDefaults(id,node,type,dimension=2,target=null){return{id,node,type,target,enabled:true,strength:1,ownerOffset:false,sourceSpace:'world',destinationSpace:'world',limitSpace:'local',channels:Object.fromEntries(constraintChannels(type).map(channel=>{const n=channelSize(channel,dimension);return[channel,{axes:Array(n).fill(true),multiplier:Array(n).fill(1),offset:Array(n).fill(0),min:Array(n).fill(null),max:Array(n).fill(null)}];})),...(type==='distance'?{distance:dimension===2?100:1,mode:'exact'}:{}),...(type==='ik'?{boneCount:2,invertDirection:false}:{}),...(type==='followPath'?{distance:0,orient:true,path:null}:{})};}
// Studio bones are segments between joint origins; the owner is the endpoint.
export function constraintChain(nodes,c){
 const byId=new Map(nodes.map(n=>[n.id,n])),chain=[c.node],seen=new Set(chain);
 if(!Number.isInteger(c.boneCount)||c.boneCount<1||c.boneCount>32)fail('IK bone count must be 1–32');
 for(let i=0;i<c.boneCount;i++){const parent=byId.get(chain[0])?.parent;if(!parent||!byId.has(parent)||seen.has(parent))fail('IK bone count exceeds the available ancestor chain');chain.unshift(parent);seen.add(parent);}return chain;
}
// IK writes ancestors, so its whole owner's constraint stack is scheduled at
// the highest affected ancestor. Descendants then see the solved chain, while
// every target (including its own constraints) is evaluated first.
export function constraintOrder(nodes,constraints){
 const byId=new Map(nodes.map(n=>[n.id,n])),anchors=new Map(),owners=new Map(),done=new Set(),visiting=new Set(),ordered=[];
 for(const c of constraints)if(c.type==='ik'){const chain=constraintChain(nodes,c),old=anchors.get(c.node);if(!old||chain.length>old.length)anchors.set(c.node,chain);}
 for(const c of constraints){const anchor=anchors.get(c.node)?.[0]??c.node;(owners.get(anchor)??(owners.set(anchor,[]),owners.get(anchor))).push(c);}
 function visit(id){if(done.has(id)||!byId.has(id))return;if(visiting.has(id))fail('cyclic target/hierarchy dependency at '+id);visiting.add(id);const n=byId.get(id);if(n.parent)visit(n.parent);for(const c of owners.get(id)??[])if(c.target){visit(c.target);if(c.type==='followPath'){const binding=byId.get(c.target)?.sprite?.boneBinding;if(binding?.enabled)for(const bone of binding.bones)visit(bone.joint);}}visiting.delete(id);done.add(id);ordered.push(...owners.get(id)??[]);}for(const n of nodes)visit(n.id);return ordered;
}
export function validateConstraints(doc,dimension=2){const constraints=doc.constraints??[],nodes=dimension===2?doc.joints:doc.nodes,ids=new Set(nodes.map(n=>n.id)),seen=new Set();if(!Array.isArray(constraints)||constraints.length>256)fail('maximum 256 constraints');for(const c of constraints){if(!c||typeof c.id!=='string'||!(/^[\w-]{1,100}$/).test(c.id)||['__proto__','constructor','prototype'].includes(c.id)||seen.has(c.id))fail('unique constraint IDs required');seen.add(c.id);if(!ids.has(c.node)||c.target!==null&&!ids.has(c.target)||c.node===c.target)fail('choose a valid owner and target');if(!CONSTRAINT_TYPES.includes(c.type)||typeof c.enabled!=='boolean'||!finite(c.strength,0,1))fail('invalid type, enabled or strength');for(const key of ['sourceSpace','destinationSpace','limitSpace'])if(!['world','local'].includes(c[key]))fail('invalid '+key);if(c.ownerOffset!==undefined&&typeof c.ownerOffset!=='boolean')fail('invalid owner offset');if(c.type==='ik'){if(dimension!==2)fail('IK chains are authored in the 2D rig');if(!c.target||typeof c.invertDirection!=='boolean')fail('IK needs a target and bend direction');constraintChain(nodes,c);}if(c.type==='followPath'){if(dimension!==2)fail('Follow Path is authored in a 2D rig');const target=nodes.find(n=>n.id===c.target),s=target?.sprite,v=doc.assets?.find(a=>a.id===s?.asset)?.vector;if(!v||c.path!==null&&!v.shapes.some(s=>s.id===c.path))fail('Follow Path needs an editable SVG target and an existing path');if(!finite(c.distance,-10000,10000)||typeof c.orient!=='boolean')fail('invalid path distance or orientation');if(s.crop||s.mesh?.enabled||s.slicing?.enabled||target.bodyJoin?.enabled||target.visual?.morph?.enabled||target.visual?.skewX||target.visual?.skewY||doc.procedural?.bindings?.some(b=>b.joint===target.id&&b.enabled!==false))fail('use an unwarped SVG path (point morphs and bone binding are supported)');}if(c.type==='distance'){if(!c.target||!finite(c.distance,0)||!['closer','further','exact'].includes(c.mode))fail('distance needs a target and a nonnegative distance');}for(const channel of constraintChannels(c.type)){const p=c.channels?.[channel],size=channelSize(channel,dimension);if(!p)fail('missing '+channel+' settings');for(const field of ['axes','multiplier','offset','min','max']){const a=p[field];if(!Array.isArray(a)||a.length!==size||a.some(v=>field==='axes'?typeof v!=='boolean':(field==='min'||field==='max')&&v===null?false:!finite(v)))fail('invalid '+channel+' '+field);}for(let i=0;i<size;i++)if(p.min[i]!==null&&p.max[i]!==null&&p.min[i]>p.max[i])fail('minimum must not exceed maximum');}}
 constraintOrder(nodes,constraints);
 for(const clip of doc.clips??[]){if(clip.constraintWeights===undefined)continue;if(!Array.isArray(clip.constraintWeights)||clip.constraintWeights.length>256)fail('invalid strength tracks');const tracks=new Set();for(const t of clip.constraintWeights){if(!seen.has(t.constraint)||tracks.has(t.constraint)||!Array.isArray(t.keys)||t.keys.length>10000)fail('invalid strength track reference');tracks.add(t.constraint);let previous=-1;for(const k of t.keys){if(!finite(k.time,0,clip.duration)||k.time<=previous||!finite(k.value,0,1)||!easeNames.includes(k.easing))fail('invalid strength key');validateBezier(k);previous=k.time;}}}
 for(const clip of doc.clips??[]){const tracks=clip.constraintTracks??[],used=new Set();if(!Array.isArray(tracks)||tracks.length>768)fail('invalid path property tracks');for(const t of tracks){const c=constraints.find(c=>c.id===t.constraint),key=t.constraint+':'+t.channel;if(c?.type!=='followPath'||!['distance','orient','ownerOffset'].includes(t.channel)||used.has(key)||!Array.isArray(t.keys))fail('invalid path property track');used.add(key);let last=-1;if(t.keys.length>10000)fail('too many path keys');for(const k of t.keys){if(!finite(k.time,0,clip.duration)||k.time<=last||!easeNames.includes(k.easing)||(t.channel==='distance'?!finite(k.value,-10000,10000):typeof k.value!=='boolean'||k.easing!=='step'))fail('invalid path property key');validateBezier(k);last=k.time;}}}
 return doc;
} 
export function constraintStrength(c,clip,time){if(!c.enabled)return 0;const keys=clip?.constraintWeights?.find(t=>t.constraint===c.id)?.keys;if(!keys?.length)return c.strength;if(time<=keys[0].time)return keys[0].value;if(time>=keys.at(-1).time)return keys.at(-1).value;const end=keys.findIndex(k=>k.time>time),a=keys[end-1],b=keys[end],t=easing((time-a.time)/(b.time-a.time),a.easing,a.bezier);return a.value+(b.value-a.value)*t;}
export function constraintValue(c,clip,time,channel){const keys=clip?.constraintTracks?.find(t=>t.constraint===c.id&&t.channel===channel)?.keys;if(!keys?.length)return c[channel];if(time<=keys[0].time)return keys[0].value;if(time>=keys.at(-1).time)return keys.at(-1).value;const i=keys.findIndex(k=>k.time>time),a=keys[i-1],b=keys[i];if(typeof a.value==='boolean')return a.value;const u=easing((time-a.time)/(b.time-a.time),a.easing,a.bezier);return a.value+(b.value-a.value)*u;}
export function pruneConstraints(doc,dimension=2){const ids=new Set((dimension===2?doc.joints:doc.nodes).map(n=>n.id));if(doc.constraints)doc.constraints=doc.constraints.filter(c=>ids.has(c.node)&&(!c.target||ids.has(c.target)));const alive=new Set(doc.constraints?.map(c=>c.id));for(const clip of doc.clips??[])for(const kind of ['constraintWeights','constraintTracks'])if(clip[kind])clip[kind]=clip[kind].filter(t=>alive.has(t.constraint));}
export function applyConstraintCommand(project,c){const dimension=c.dimension??2;if(![2,3].includes(dimension))fail('invalid dimension');const source=dimension===2?project:project.scene3d;if(!source)fail('open a scene first');const doc={...source,constraints:structuredClone(source.constraints??[]),clips:structuredClone(source.clips)},list=doc.constraints,at=list.findIndex(x=>x.id===c.id);let id=c.id;
 if(c.op==='constraint.add'){if(at>=0)fail('duplicate ID');id=c.id;if(!id){let i=1;while(list.some(x=>x.id==='constraint-'+i))i++;id='constraint-'+i;}list.push({...constraintDefaults(id,c.node,c.type,dimension,c.target??null),...structuredClone(c.values??{}),id,node:c.node,type:c.type});}
 else if(at<0)fail('missing constraint');
 else if(c.op==='constraint.update'){for(const key of Object.keys(c.values??{}))if(!['target','enabled','strength','ownerOffset','sourceSpace','destinationSpace','limitSpace','channels','distance','mode','boneCount','invertDirection','orient','path'].includes(key))fail('unknown property '+key);Object.assign(list[at],structuredClone(c.values));}
 else if(c.op==='constraint.remove'){list.splice(at,1);for(const clip of doc.clips)for(const kind of ['constraintWeights','constraintTracks'])if(clip[kind])clip[kind]=clip[kind].filter(t=>t.constraint!==c.id);}
 else if(c.op==='constraint.order'){if(!Number.isInteger(c.index)||c.index<0||c.index>=list.length)fail('invalid order');list.splice(c.index,0,list.splice(at,1)[0]);}
 else if(c.op==='constraint.key'){const clip=doc.clips.find(x=>x.id===c.clip);if(!clip)fail('choose an animation');const channel=c.channel??'strength',kind=channel==='strength'?'constraintWeights':'constraintTracks';clip[kind]??=[];let track=clip[kind].find(t=>t.constraint===c.id&&(t.channel??'strength')===channel);if(!track){track={constraint:c.id,...(kind==='constraintTracks'?{channel}:{}),keys:[]};clip[kind].push(track);}track.keys=track.keys.filter(k=>Math.abs(k.time-c.time)>1e-6);if(!c.remove)track.keys.push({time:c.time,value:c.value,easing:c.easing??(typeof c.value==='boolean'?'step':'linear')});track.keys.sort((a,b)=>a.time-b.time);if(!track.keys.length)clip[kind]=clip[kind].filter(t=>t!==track);}
 else fail('unknown command');
 validateConstraints(doc,dimension);source.constraints=list;source.clips=doc.clips;return id;
}
