import test from 'node:test';
import assert from 'node:assert/strict';
import {constraintDefaults,validateConstraints,applyConstraintCommand,constraintStrength} from '../src/puppet-studio/constraints/model.js';
import {solveConstraints3D} from '../src/puppet-studio/constraints/solve3d.js';
const node=(id,position=[0,0,0],parent=null,rotation=[0,0,0],scale=[1,1,1])=>({id,parent,position,rotation,scale});
const close=(actual,expected)=>actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-6,`${actual} ≠ ${expected}`));
const c=(type='translation',target='target')=>constraintDefaults('c','owner',type,3,target);
test('world-space copying converts through translated, rotated and scaled parents',()=>{const nodes=[node('parent',[10,0,0],null,[0,0,90],[2,2,2]),node('owner',[0,0,0],'parent'),node('target',[10,6,0])];close(solveConstraints3D(nodes,[c()],null,0).get('owner').position,[3,0,0]);});
test('local/source and world/destination are independent; limits use their own space',()=>{const nodes=[node('parent',[10,0,0]),node('owner',[0,0,0],'parent'),node('target',[3,4,0],'parent')],v=c();v.sourceSpace='local';v.limitSpace='world';v.channels.position.max[1]=2;close(solveConstraints3D(nodes,[v],null,0).get('owner').position,[-7,2,0]);});
test('axis masks, multipliers, offsets and strength compose without touching other channels',()=>{const nodes=[node('owner',[2,3,4],null,[0,0,30]),node('target',[10,20,30])],v=c();v.destinationSpace=v.sourceSpace=v.limitSpace='local';v.channels.position.axes[1]=false;v.channels.position.multiplier[0]=-2;v.channels.position.offset[0]=5;v.strength=.5;const r=solveConstraints3D(nodes,[v],null,0).get('owner');close(r.position,[-6.5,3,17]);close(r.rotation,[0,0,30]);close(r.scale,[1,1,1]);});
test('standalone limits and distance closer/further/exact, including coincident points',()=>{const nodes=[node('owner',[10,0,0]),node('target')],v=c('translation',null);v.channels.position.max[0]=4;close(solveConstraints3D(nodes,[v],null,0).get('owner').position,[4,0,0]);const d=c('distance');d.distance=3;for(const mode of ['closer','exact']){d.mode=mode;close(solveConstraints3D(nodes,[d],null,0).get('owner').position,[3,0,0]);}d.mode='further';assert.equal(solveConstraints3D(nodes,[d],null,0).size,0);close(solveConstraints3D([node('owner'),node('target')],[d],null,0).get('owner').position,[3,0,0]);});
test('rotation, scale and full transform copy; disabled and zero strength do nothing',()=>{const nodes=[node('owner'),node('target',[1,2,3],null,[10,20,30],[2,3,4])];for(const type of ['rotation','scale','transform']){const v=c(type);v.sourceSpace=v.destinationSpace=v.limitSpace='local';const r=solveConstraints3D(nodes,[v],null,0).get('owner');if(type!=='scale')close(r.rotation,[10,20,30]);if(type!=='rotation')close(r.scale,[2,3,4]);}const v=c();v.enabled=false;assert.equal(solveConstraints3D(nodes,[v],null,0).size,0);v.enabled=true;v.strength=0;assert.equal(solveConstraints3D(nodes,[v],null,0).size,0);});
test('target chains resolve independent of declaration order; per-owner constraint order is preserved',()=>{const nodes=[node('owner'),node('middle'),node('target',[8,0,0])],a=c('translation','middle'),b={...c(),id:'b',node:'middle'},limit={...c('translation',null),id:'limit'};limit.channels.position.max[0]=5;close(solveConstraints3D(nodes,[a,b,limit],null,0).get('owner').position,[5,0,0]);close(solveConstraints3D(nodes,[limit,a,b],null,0).get('owner').position,[8,0,0]);});
test('cycles, descendant targets, missing nodes, limits and malformed strength keys are rejected transactionally',()=>{const project={scene3d:{nodes:[node('owner'),node('target')],clips:[{id:'idle',duration:2}],constraints:[c()]}},before=JSON.stringify(project);assert.throws(()=>applyConstraintCommand(project,{op:'constraint.add',dimension:3,id:'back',node:'target',type:'translation',target:'owner'}),/cyclic/);assert.equal(JSON.stringify(project),before);project.scene3d.nodes[1].parent='owner';assert.throws(()=>validateConstraints(project.scene3d,3),/cyclic/);project.scene3d.nodes[1].parent=null;project.scene3d.constraints[0].channels.position.min[0]=5;project.scene3d.constraints[0].channels.position.max[0]=1;assert.throws(()=>validateConstraints(project.scene3d,3),/minimum/);});
test('strength keys interpolate deterministically and commands retain defaults outside keyed clips',()=>{const p={scene3d:{nodes:[node('owner'),node('target',[10,0,0])],clips:[{id:'idle',duration:2}],constraints:[c()]}};for(const [time,value]of [[0,0],[2,1]])applyConstraintCommand(p,{op:'constraint.key',dimension:3,id:'c',clip:'idle',time,value});assert.equal(constraintStrength(c(),p.scene3d.clips[0],1),.5);assert.equal(constraintStrength(c(),null,1),1);close(solveConstraints3D(p.scene3d.nodes,p.scene3d.constraints,p.scene3d.clips[0],1).get('owner').position,[5,0,0]);});

test('zero scale limits remain finite and invertible in world space',()=>{const nodes=[node('owner'),node('target')],v=c('scale');v.channels.scale.multiplier=[0,0,0];const r=solveConstraints3D(nodes,[v],null,0).get('owner');assert.ok([...r.position,...r.rotation,...r.scale].every(Number.isFinite));assert.ok(r.scale.every(v=>v>0));});
