import test from 'node:test';
import assert from 'node:assert/strict';
import {newStateMachine,createStateMachine,validateStateMachines,applyStateMachineCommand,blendMachineLayers} from '../src/puppet-studio/state-machine.js';
function fixture(){const p={clips:[{id:'idle',name:'Idle',duration:2,loop:true},{id:'run',name:'Run',duration:1,loop:false}]},m=newStateMachine('m',2,p.clips[0]);m.inputs=[{id:'go',name:'Go',type:'trigger'},{id:'speed',name:'Speed',type:'number',value:0},{id:'ready',name:'Ready',type:'boolean',value:true}];m.layers[0].states=[{id:'idle',name:'Idle',type:'animation',clip:'idle',speed:1,playback:'clip',x:0,y:0},{id:'run',name:'Run',type:'animation',clip:'run',speed:1,playback:'clip',x:200,y:0},{id:'blank',name:'Blank',type:'blank',x:400,y:0}];m.layers[0].entry='idle';p.stateMachines=[m];return p;}
const edge=(patch={})=>({id:'edge',from:'idle',to:'run',enabled:true,duration:.5,easing:'linear',exitTime:null,conditions:[{input:'go',op:'fired'}],...patch});
test('trigger crossfade advances both clips, consumes input, and leaves authoring data untouched',()=>{const p=fixture();p.stateMachines[0].layers[0].transitions=[edge()];const before=JSON.stringify(p),r=createStateMachine(p,'m');r.advance(.3);r.fire('go');const f=r.advance(.25);assert.equal(f.layers[0].state,'run');assert.deepEqual(f.layers[0].samples,[{state:'idle',clip:'idle',time:.55,weight:.5},{state:'run',clip:'run',time:.25,weight:.5}]);assert.equal(f.inputs.go,false);assert.equal(f.events[0].type,'transition');assert.equal(r.advance(.25).layers[0].samples.length,1);assert.equal(JSON.stringify(p),before);r.reset();assert.equal(r.snapshot().layers[0].state,'idle');});
test('numeric and boolean conditions are ANDed; first eligible arrow has priority',()=>{const p=fixture(),l=p.stateMachines[0].layers[0];l.transitions=[edge({id:'first',conditions:[{input:'speed',op:'gt',value:3},{input:'ready',op:'eq',value:true}]}),edge({id:'second',to:'blank',conditions:[{input:'speed',op:'gt',value:1}]})];const r=createStateMachine(p,'m');r.setInput('speed',4).setInput('ready',false);assert.equal(r.advance(0).layers[0].state,'blank');r.reset();r.setInput('speed',4);assert.equal(r.advance(0).layers[0].state,'run');assert.throws(()=>r.setInput('speed',NaN));assert.throws(()=>r.setInput('go',true));});
test('exit-time carries overshoot, supports reverse and one-shot clamping',()=>{const p=fixture(),l=p.stateMachines[0].layers[0];l.transitions=[edge({exitTime:1,conditions:[]})];const r=createStateMachine(p,'m');r.advance(1.9);const f=r.advance(.3).layers[0];assert.equal(f.state,'run');assert.ok(Math.abs(f.elapsed-.2)<1e-9);assert.ok(Math.abs(f.samples[1].weight-.4)<1e-9);assert.equal(r.advance(4).layers[0].samples[0].time,1);l.states[0].speed=-1;const backwards=createStateMachine(p,'m');assert.equal(backwards.advance(.25).layers[0].samples[0].time,1.75);});
test('triggers fan out across enabled layers; any state does not restart itself; exit is terminal',()=>{const p=fixture(),l=p.stateMachines[0].layers[0];l.transitions=[edge({from:'any',duration:0})];const other=structuredClone(l);other.id='second';const off=structuredClone(l);off.id='disabled';off.enabled=false;p.stateMachines[0].layers.push(other,off);const r=createStateMachine(p,'m');r.fire('go');assert.deepEqual(r.advance(0).layers.map(l=>l.state),['run','run']);r.fire('go');assert.equal(r.advance(.3).layers[0].elapsed,.3);l.transitions.push(edge({id:'exit-edge',from:'run',to:'exit',duration:0,conditions:[],exitTime:1}));const terminal=createStateMachine(p,'m');terminal.fire('go').advance(0);assert.equal(terminal.advance(1).layers[0].state,'exit');assert.deepEqual(terminal.advance(3).layers[0].samples,[]);});
test('crossfade finishes before another transition; disabled transitions are skipped',()=>{const p=fixture(),l=p.stateMachines[0].layers[0];l.transitions=[edge({id:'off',enabled:false,to:'blank'}),edge(),edge({id:'back',from:'run',to:'idle',conditions:[],duration:0})];const r=createStateMachine(p,'m');r.fire('go');r.advance(.1);assert.equal(r.advance(.2).layers[0].state,'run');assert.equal(r.advance(.2).layers[0].state,'idle');});
test('validation rejects corrupt graphs and missing clips transactionally',()=>{const p=fixture();validateStateMachines(JSON.parse(JSON.stringify(p)));for(const mutate of [m=>m.layers[0].entry='missing',m=>m.layers[0].states[0].clip='missing',m=>m.inputs[0].id='__proto__',m=>m.layers[0].transitions=[edge({conditions:[{input:'missing',op:'fired'}]})],m=>m.layers[0].states[0].speed=Infinity,m=>m.layers[0].transitions=[edge({to:'missing'})]]){const value=structuredClone(p.stateMachines[0]);mutate(value);const before=JSON.stringify(p);assert.throws(()=>applyStateMachineCommand(p,{op:'stateMachine.put',value}),/State machine/);assert.equal(JSON.stringify(p),before);}assert.throws(()=>createStateMachine(p,'m').advance(-1));});
test('sparse layers blend against rest or underlying layers, including blank and exit fades',()=>{const values={base:[{node:'body',channel:'x',value:10},{node:'arm',channel:'x',value:20}],top:[{node:'arm',channel:'x',value:100}]},sample=s=>values[s.clip],rest=()=>0,frame={layers:[{samples:[{clip:'base',weight:1}]},{samples:[{clip:'top',weight:.25}]}]};assert.deepEqual(blendMachineLayers(frame,sample,rest),[{node:'body',channel:'x',value:10},{node:'arm',channel:'x',value:40}]);frame.layers[1].samples=[];assert.equal(blendMachineLayers(frame,sample,rest)[1].value,20);});
