// Marching triangles with shared edge identities. A centre sample resolves
// saddle cells consistently; stitched rings preserve islands and holes.
export function traceField(field,bounds,resolution=128){const n=resolution,h=bounds.size/n,segments=[],vertices=new Map(),values=new Float64Array((n+1)*(n+1)),coords=new Map();
 const vertex=(id,x,y)=>{coords.set(id,[x,y]);return id;};for(let y=0;y<=n;y++)for(let x=0;x<=n;x++){const id=y*(n+1)+x,px=bounds.min[0]+x*h,py=bounds.min[1]+y*h;vertex(id,px,py);values[id]=field(px,py);}
 const sample=id=>id<values.length?values[id]:field(...coords.get(id));const edge=(a,b,va,vb)=>{const key=a<b?a+':'+b:b+':'+a;if(!vertices.has(key)){const t=va/(va-vb),p=coords.get(a),q=coords.get(b);vertices.set(key,[p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t]);}return key;};
 for(let y=0;y<n;y++)for(let x=0;x<n;x++){const a=y*(n+1)+x,b=a+1,d=a+n+1,c=d+1,center=values.length+y*n+x;vertex(center,bounds.min[0]+(x+.5)*h,bounds.min[1]+(y+.5)*h);const corners=[a,b,c,d];for(let i=0;i<4;i++){const tri=[corners[i],corners[(i+1)%4],center],hits=[];for(let j=0;j<3;j++){const p=tri[j],q=tri[(j+1)%3],v=sample(p),w=sample(q);if((v<=0)!==(w<=0))hits.push(edge(p,q,v,w));}if(hits.length===2)segments.push(hits);}}
 const links=new Map();for(const [a,b]of segments){(links.get(a)??(links.set(a,[]),links.get(a))).push(b);(links.get(b)??(links.set(b,[]),links.get(b))).push(a);}const used=new Set(),rings=[];
 for(const first of links.keys()){if(used.has(first))continue;let current=first,previous=null,ring=[],closed=false;while(current&&!used.has(current)){used.add(current);ring.push(vertices.get(current));const next=links.get(current)?.find(k=>k!==previous);previous=current;current=next;if(current===first){closed=true;break;}}if(!closed)throw Error('Surface reaches the sampling boundary; enlarge the field bounds');if(ring.length>2){ring=simplifyRing(ring,h*.12);if(ring.length>2)rings.push(ring);}}return rings;}
function simplifyRing(ring,tolerance){const distance=(p,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],u=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p[0]-a[0]-u*dx,p[1]-a[1]-u*dy);};const simplify=pts=>{let max=0,index=0;for(let i=1;i<pts.length-1;i++){const d=distance(pts[i],pts[0],pts.at(-1));if(d>max){max=d;index=i;}}return max>tolerance?simplify(pts.slice(0,index+1)).slice(0,-1).concat(simplify(pts.slice(index))):[pts[0],pts.at(-1)];};const mid=Math.floor(ring.length/2);return simplify(ring.slice(0,mid+1)).slice(0,-1).concat(simplify([...ring.slice(mid),ring[0]]).slice(0,-1));}
