import {easing} from '../fx/math.js';
const fail=m=>{throw Error('Shape Lab: '+m);},finite=(v,min,max)=>Number.isFinite(v)&&v>=min&&v<=max;
export const SHAPE_COMMANDS=['shapeLab.create','shapeLab.settings','shapeLab.part','shapeLab.removePart','shapeLab.key','shapeLab.delete','shapeLab.bake'];
export const partDefaults=(id='blob')=>({id,name:id,type:'ball',operation:'union',position:[0,0,0],size:[.7,.7,.7],radius:.7,angle:0});
export function shapeRecipe(id='blobs',dimension=2){return{id,name:dimension+'D merging blobs',dimension,mode:'sdf',blend:.6,color:'#72c4b1',duration:2,fps:12,loop:true,resolution:dimension===2?128:28,parts:[{...partDefaults('a'),position:[-.85,0,0]},{...partDefaults('b'),position:[.85,0,0]}],tracks:[{part:'b',channel:'position',keys:[{time:0,value:[.85,0,0],easing:'smooth'},{time:1,value:[.1,.25,0],easing:'smooth'},{time:2,value:[.85,0,0],easing:'smooth'}]}]};}
export function validateRecipe(r){
 if(!r||!/^[-\w]{1,80}$/.test(r.id)||r.id in Object.prototype||typeof r.name!=='string'||r.name.length>120||![2,3].includes(r.dimension)||!['sdf','metaballs'].includes(r.mode)||!/^#[\da-f]{6}$/i.test(r.color))fail('invalid recipe');
 for(const [v,min,max,label]of [[r.blend,0,4,'blend'],[r.duration,.1,10,'duration'],[r.fps,1,30,'fps'],[r.resolution, r.dimension===2?32:12,r.dimension===2?256:48,'resolution']])if(!finite(v,min,max))fail('invalid '+label);
 if(!Number.isInteger(r.fps)||!Number.isInteger(r.resolution)||typeof r.loop!=='boolean'||!Array.isArray(r.parts)||r.parts.length<1||r.parts.length>24)fail('invalid sampling settings or primitive count');
 const ids=new Set();for(const p of r.parts){if(!p||!/^[-\w]{1,80}$/.test(p.id)||p.id in Object.prototype||ids.has(p.id)||typeof p.name!=='string'||p.name.length>120||!['ball','box','capsule','ring','path'].includes(p.type)||!['union','subtract','intersect'].includes(p.operation))fail('invalid primitive');ids.add(p.id);if(p.type==='path'&&(!['evenodd','nonzero'].includes(p.fillRule)||!Array.isArray(p.contours)||!p.contours.length||p.contours.length>64||p.contours.flat().length>4096||p.contours.some(r=>!Array.isArray(r)||r.length<3||r.some(v=>!Array.isArray(v)||v.length!==2||v.some(n=>!finite(n,-20,20))))))fail('invalid imported outline');if(r.mode==='metaballs'&&(p.type!=='ball'||p.operation!=='union'))fail('Metaballs use additive balls; use SDF for other shapes or operations');checkValue('position',p.position);checkValue('size',p.size);checkValue('radius',p.radius);checkValue('angle',p.angle);}
 if(r.parts[0].operation!=='union')fail('the first primitive must be additive');
 if(!Array.isArray(r.tracks)||r.tracks.length>125)fail('too many tracks');const seen=new Set();for(const t of r.tracks){const key=t.part+':'+t.channel;if(seen.has(key)||!ids.has(t.part)&&!(t.part===null&&t.channel==='blend')||!['position','size','radius','angle','blend'].includes(t.channel)||t.channel==='blend'&&t.part!==null||!Array.isArray(t.keys)||t.keys.length>300)fail('invalid animation track');seen.add(key);let last=-1;for(const k of t.keys){if(!finite(k.time,0,r.duration)||k.time<=last||!['linear','smooth','step'].includes(k.easing))fail('invalid key');checkValue(t.channel,k.value);last=k.time;}}return r;
}
function checkValue(channel,v){const limits={position:[-20,20],size:[.03,8],radius:[.03,8],angle:[-3600,3600],blend:[0,4]},[min,max]=limits[channel];if(['position','size'].includes(channel)){if(!Array.isArray(v)||v.length!==3||v.some(n=>!finite(n,min,max)))fail('invalid '+channel);}else if(!finite(v,min,max))fail('invalid '+channel);}
export function validateShapeLab(p){if(p.shapeLab===undefined)return;const s=p.shapeLab;if(!s||s.version!==1||!Array.isArray(s.recipes)||s.recipes.length>16)fail('invalid workspace');const ids=new Set();for(const r of s.recipes){validateRecipe(r);if(ids.has(r.id))fail('duplicate recipe');ids.add(r.id);}}
export function sampleRecipe(r,time){const out={...r,parts:r.parts.map(p=>({...p}))},t=Math.max(0,Math.min(r.duration,time));for(const track of r.tracks){if(!track.keys.length)continue;const keys=track.keys;let a=keys[0],b=null;for(const k of keys){if(k.time<=t)a=k;else{b=k;break;}}let u=b?easing(Math.max(0,(t-a.time)/(b.time-a.time)),a.easing):0;const value=b?(Array.isArray(a.value)?a.value.map((v,i)=>v+(b.value[i]-v)*u):a.value+(b.value-a.value)*u):structuredClone(a.value);const target=track.part===null?out:out.parts.find(p=>p.id===track.part);target[track.channel]=value;}return out;}
export function applyShapeCommand(project,c){const lab=structuredClone(project.shapeLab??{version:1,recipes:[]});let r=lab.recipes.find(r=>r.id===c.id);if(c.op==='shapeLab.create'){if(r)fail('duplicate recipe');r=c.value?structuredClone(c.value):shapeRecipe(c.id,c.dimension??2);lab.recipes.push(r);}else if(!r)fail('select a recipe');else if(c.op==='shapeLab.settings'){const allowed=['name','mode','blend','color','duration','fps','loop','resolution'];for(const k of Object.keys(c.values))if(!allowed.includes(k))fail('unknown setting');if(c.values.duration!==undefined)for(const t of r.tracks)for(const k of t.keys)k.time*=c.values.duration/r.duration;Object.assign(r,c.values);}else if(c.op==='shapeLab.part'){let p=r.parts.find(p=>p.id===c.part);if(!p){p=partDefaults(c.part);r.parts.push(p);}for(const k of Object.keys(c.values))if(!['name','type','operation','position','size','radius','angle','contours','fillRule'].includes(k))fail('unknown primitive property');Object.assign(p,structuredClone(c.values));}else if(c.op==='shapeLab.removePart'){r.parts=r.parts.filter(p=>p.id!==c.part);r.tracks=r.tracks.filter(t=>t.part!==c.part);if(r.parts[0])r.parts[0].operation='union';}else if(c.op==='shapeLab.key'){let t=r.tracks.find(t=>t.part===c.part&&t.channel===c.channel);if(!t){t={part:c.part,channel:c.channel,keys:[]};r.tracks.push(t);}t.keys=t.keys.filter(k=>Math.abs(k.time-c.time)>1e-6);if(!c.remove)t.keys.push({time:c.time,value:structuredClone(c.value),easing:c.easing??'smooth'});t.keys.sort((a,b)=>a.time-b.time);}else if(c.op==='shapeLab.delete')lab.recipes=lab.recipes.filter(v=>v.id!==c.id);else fail('unknown command');validateShapeLab({shapeLab:lab});project.shapeLab=lab;return r.id;}
