import {validateBezier} from '../authoring/easing.js';
import {CHANNELS,identity,clamp,point,inverse} from '../joint-transforms.js';
import {parameter,easing,easeNames} from '../fx/math.js';
export function toolPoint(tool,time){const keys=tool.pointKeys;if(!keys?.length)return tool.point;if(time<=keys[0].time)return keys[0].value;if(time>=keys.at(-1).time)return keys.at(-1).value;const i=keys.findIndex(k=>k.time>time),a=keys[i-1],b=keys[i],t=easing((time-a.time)/(b.time-a.time),({in:'in-cubic',out:'out-cubic',back:'out-back',elastic:'out-elastic'}[a.easing]??a.easing??'linear'),a.bezier);return a.value.map((v,k)=>v+(b.value[k]-v)*t);}
export const FOLLOW_PRESETS={subtle:{lagFrames:2,strength:.35},natural:{lagFrames:3,strength:.65},loose:{lagFrames:5,strength:.9}};
export const shortAngle=(a,b)=>((b-a+540)%360+360)%360-180;
export function influence(item,time,duration){if(item.enabled===false||time<(item.start??0)||time>(item.end??duration))return 0;const blend=item.blend??0,start=item.start??0,end=item.end??duration;const smooth=x=>{x=clamp(x,0,1);return x*x*(3-2*x);};return clamp(parameter(item.weight,time,1),0,1)*(blend?Math.min(start>0?smooth((time-start)/blend):1,end<duration?smooth((end-time)/blend):1):1);}
export function poseLayers(transforms,tools,time,duration,sampleClip){const layers=tools?.layers??[],solo=layers.some(l=>l.solo&&l.enabled!==false);for(const layer of layers){if(solo&&!layer.solo)continue;const w=influence(layer,time,duration);if(!w)continue;const values=layer.sourceClip&&sampleClip?sampleClip(layer,time):layer.values;for(const [id,value]of Object.entries(values)){const t=transforms.get(id);if(!t)continue;for(const c of CHANNELS){if(value[c]===undefined)continue;if(c.startsWith('scale'))t[c]*=Math.max(.01,1+(value[c]-1)*w);else t[c]+=value[c]*w;}}}}
// Constraints are sampled afresh from authored animation; scrubbing and reverse
// playback produce the same pose without carrying a solver's previous frame.
export function solvePoseTools(project,clip,time,pose,transforms,sampleBase){const tools=clip?.tools;if(!tools)return;const duration=clip.duration;
 for(const f of tools.follow??[]){const w=influence(f,time,duration);if(!w)continue;const p=pose.get(f.joint),source=f.source??p?.joint.parent;if(!p||!source)continue;const lag=(f.lagFrames??3)/clip.fps,wrap=t=>clip.loop?(t%duration+duration)%duration:Math.max(0,t),now=sampleBase(time).get(source),old=sampleBase(wrap(time-lag)).get(source);if(!now||!old)continue;const rotation=m=>Math.atan2(m[1],m[0])*180/Math.PI,amount=clamp(shortAngle(rotation(now.world),rotation(old.world)),-(f.limit??45),f.limit??45);transforms.get(f.joint).rotation+=amount*w*(f.strength??.65);pose.updateBranch(f.joint);}
 const origin=(id,offset=[0,0])=>point(pose.get(id).world,{x:offset[0],y:offset[1]});
 function aim(id,end,target,offset,w=1){const p=pose.get(id),pm=p.joint.parent?pose.get(p.joint.parent).world:[1,0,0,1,0,0],inv=inverse(pm),a=point(inv,origin(id)),b=point(inv,origin(end,offset)),g=point(inv,target);if(Math.hypot(g.x-a.x,g.y-a.y)<1e-7)return;const delta=shortAngle(Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI,Math.atan2(g.y-a.y,g.x-a.x)*180/Math.PI);transforms.get(id).rotation+=delta*w;pose.updateBranch(id);}
 // Accumulate shared support before applying it, so two hands cannot make
 // solve order choose which shoulder/torso direction wins.
 const support=new Map();for(const c of tools.constraints??[]){if(!c.assist||!c.chain)continue;const w=influence(c,time,duration),root=pose.get(c.chain.root),id=root?.joint.parent;if(!w||!id)continue;const pm=pose.get(id).joint.parent?pose.get(pose.get(id).joint.parent).world:[1,0,0,1,0,0],inv=inverse(pm),a=point(inv,origin(id)),b=point(inv,origin(c.joint,c.origin)),g=point(inv,c.target?origin(c.target,toolPoint(c,time)):{x:toolPoint(c,time)[0],y:toolPoint(c,time)[1]}),delta=shortAngle(Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI,Math.atan2(g.y-a.y,g.x-a.x)*180/Math.PI),limit=c.supportLimit??6,entry=support.get(id)??{angle:0,limit};entry.angle+=delta*w*.25;entry.limit=Math.max(entry.limit,limit);support.set(id,entry);}for(const [id,s]of support){transforms.get(id).rotation+=clamp(s.angle,-s.limit,s.limit);pose.updateBranch(id);}
 for(const c of [...(tools.constraints??[])].sort((a,b)=>(a.type==='look'?0:1)-(b.type==='look'?0:1))){const w=influence(c,time,duration),p=pose.get(c.joint);if(!w||!p)continue;const at=origin(c.joint,c.origin),target=c.target?origin(c.target,toolPoint(c,time)):{x:toolPoint(c,time)[0],y:toolPoint(c,time)[1]};
  if(c.type==='look'){const pm=p.joint.parent?pose.get(p.joint.parent).world:[1,0,0,1,0,0],g=point(inverse(pm),target),t=transforms.get(c.joint),direction=Math.atan2(g.y-t.y,g.x-t.x)*180/Math.PI;const forward=(c.forward??0)+(t.scaleX<0?180:0),change=clamp(shortAngle(t.rotation+forward,direction),-(c.limit??70),c.limit??70);if(Math.hypot(g.x-t.x,g.y-t.y)>1e-6){t.rotation+=change*w;pose.updateBranch(c.joint);}continue;}
  const desired={x:c.type==='ground'?at.x:at.x+(target.x-at.x)*w,y:at.y+(target.y-at.y)*w};
  if(c.chain){
   const root=pose.get(c.chain.root),pm=root.joint.parent?pose.get(root.joint.parent).world:[1,0,0,1,0,0],inv=inverse(pm),a=point(inv,origin(c.chain.root)),b=point(inv,origin(c.chain.mid)),e=point(inv,at),g=point(inv,desired),l1=Math.hypot(b.x-a.x,b.y-a.y),l2=Math.hypot(e.x-b.x,e.y-b.y),distance=Math.hypot(g.x-a.x,g.y-a.y);
   if(l1>.001&&l2>.001){const d=clamp(distance,Math.abs(l1-l2)+.0001,l1+l2-.0001),side=Math.sign((b.x-a.x)*(e.y-a.y)-(b.y-a.y)*(e.x-a.x))||1,angle=Math.atan2(g.y-a.y,g.x-a.x)-side*Math.acos(clamp((l1*l1+d*d-l2*l2)/(2*l1*d),-1,1)),elbow=point(pm,{x:a.x+Math.cos(angle)*l1,y:a.y+Math.sin(angle)*l1});aim(c.chain.root,c.chain.mid,elbow,[0,0]);}
   for(let i=0;i<48;i++){aim(c.chain.mid,c.joint,desired,c.origin);aim(c.chain.root,c.joint,desired,c.origin);const e=origin(c.joint,c.origin);if(Math.hypot(e.x-desired.x,e.y-desired.y)<.02)break;}}
  else{const pm=p.joint.parent?pose.get(p.joint.parent).world:[1,0,0,1,0,0],inv=inverse(pm),a=point(inv,at),b=point(inv,desired),t=transforms.get(c.joint);t.x+=b.x-a.x;t.y+=b.y-a.y;pose.updateBranch(c.joint);}
  p.contactTarget=desired;const actual=origin(c.joint,c.origin);p.contactError=Math.hypot(actual.x-desired.x,actual.y-desired.y);
 }
}
export function ghostTimes(clip,time,{mode='keys',spacing=.15}={}){const values=Array.isArray(clip.tracks)?clip.tracks.flatMap(t=>t.keys.map(k=>k.time)):Object.values(clip.tracks).flatMap(t=>t.map(k=>k.time)),keys=[...new Set(values)].sort((a,b)=>a-b);return mode==='keys'?[keys.filter(t=>t<time-1e-5).at(-1),keys.find(t=>t>time+1e-5)].filter(t=>t!==undefined):[Math.max(0,time-spacing),Math.min(clip.duration,time+spacing)].filter(t=>Math.abs(t-time)>1e-5);}
export function cleanToolReferences(clip,ids){if(!clip.tools)return;for(const key of ['constraints','follow'])if(clip.tools[key])clip.tools[key]=clip.tools[key].filter(x=>ids.has(x.joint)&&(!x.target||ids.has(x.target))&&(!x.source||ids.has(x.source))&&(!x.chain||ids.has(x.chain.root)&&ids.has(x.chain.mid)));for(const layer of clip.tools.layers??[]) {if(layer.joints)layer.joints=layer.joints.filter(id=>ids.has(id));}for(const layer of clip.tools.layers??[])for(const id of Object.keys(layer.values))if(!ids.has(id))delete layer.values[id];}
export function validateTools(tools,nodes,duration,dimension=2,clips=[]){if(!tools)return;const fail=m=>{throw Error('Motion tools: '+m);},ids=new Set(nodes.map(n=>n.id)),num=(v,min,max)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max,seen=new Set();for(const key of ['layers','constraints','follow']){if(tools[key]===undefined)continue;if(!Array.isArray(tools[key])||tools[key].length>64)fail('maximum 64 '+key);for(const item of tools[key]){if(typeof item.id!=='string'||!item.id||seen.has(item.id))fail('unique IDs required');seen.add(item.id);if(!num(item.start??0,0,duration)||!num(item.end??duration,item.start??0,duration)||!num(item.blend??0,0,120))fail('invalid interval');if(Array.isArray(item.weight)){let previous=-1;for(const p of item.weight){if(!num(p.time,0,duration)||p.time<=previous||!num(p.value,0,1))fail('invalid influence keys');previous=p.time;}}else if(!num(item.weight??1,0,1))fail('influence must be 0–1');
 if(key==='layers'){if(item.sourceClip){if(!clips.some(c=>c.id===item.sourceClip))fail('missing layer animation');if(!Array.isArray(item.joints)||item.joints.some(id=>!ids.has(id)))fail('invalid layer mask');if(!num(item.speed??1,.05,8)||!num(item.offset??0,0,120))fail('invalid layer timing');}if(!item.values||Array.isArray(item.values)||typeof item.values!=='object')fail('pose values required');for(const [id,values]of Object.entries(item.values)){if(!ids.has(id))fail('missing pose joint');for(const [channel,value]of Object.entries(values)){const channels=dimension===2?CHANNELS:['position','rotation','scale','deform.stretch','deform.waist','deform.bend','deform.taper'];if(!channels.includes(channel))fail('invalid pose channel');const length=dimension===2?0:['position','rotation','scale'].includes(channel)?3:channel==='deform.bend'?2:0;if(length&&(!Array.isArray(value)||value.length!==length))fail('invalid pose vector');if((Array.isArray(value)?value:[value]).some(v=>!num(v,channel.startsWith('scale')?.01:-100000,100000)))fail('invalid pose value');}}}
 else{if(!ids.has(item.joint))fail('missing driven joint');if(item.source&&!ids.has(item.source))fail('missing follow source');if(item.target){if(!ids.has(item.target))fail('missing target');let target=nodes.find(n=>n.id===item.target);while(target){if(target.id===item.joint)fail('target must be outside the driven branch');target=nodes.find(n=>n.id===target.parent);}}if(key==='follow'){if(!num(item.lagFrames??3,0,30)||!num(item.strength??.65,0,1)||!num(item.limit??45,0,180))fail('invalid follow-through');}
 else{if(!['look','pin','ground'].includes(item.type))fail('unknown constraint');for(const k of ['point','origin'])if(k==='point'||item[k]!==undefined){if(!Array.isArray(item[k])||item[k].length!==dimension||item[k].some(v=>!num(v,-100000,100000)))fail('invalid '+k);}if(item.pointKeys!==undefined){if(!Array.isArray(item.pointKeys)||item.pointKeys.length>10000)fail('invalid target keys');let previous=-1;for(const k of item.pointKeys){if(!num(k.time,0,duration)||k.time<=previous||!Array.isArray(k.value)||k.value.length!==dimension||k.value.some(v=>!num(v,-100000,100000))||![...easeNames,'in','out','back','elastic'].includes(k.easing))fail('invalid target key');validateBezier(k);previous=k.time;}}if(!num(item.supportLimit??6,0,20))fail('invalid support angle');if(!num(item.limit??70,0,180)||!num(item.forward??0,-360,360))fail('invalid look limit');if(item.chain){const end=nodes.find(n=>n.id===item.joint),mid=nodes.find(n=>n.id===item.chain.mid);if(!mid||end.parent!==mid.id||mid.parent!==item.chain.root||!ids.has(item.chain.root))fail('contact needs a connected two-bone chain');}if(dimension===3&&nodes.find(n=>n.id===item.joint)?.attachment)fail('edit the puppet joint to constrain a socket attachment');}}
 }}}
