import {easing} from '../fx/math.js';
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
export const NOODLE_COMMANDS=['noodle.set','noodle.key','noodle.remove','noodle.bind','noodle.bake'];
export const noodleDefaults=()=>({enabled:true,points:[[0,-.5,0],[0,-1/6,0],[0,1/6,0],[0,.5,0]],widths:[1,1,1,1],twists:[0,0,0,0],stretch:1,thickness:1,turn:0,volume:true,lag:0,spring:0,faces:{}});
export const noodlePose=n=>Object.fromEntries(['points','widths','twists','stretch','thickness','turn'].map(k=>[k,structuredClone(n[k])]));
const fail=s=>{throw Error('Noodle: '+s);},num=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b;
export function validateNoodle(n){if(!n)return;if(typeof n.enabled!=='boolean'||typeof n.volume!=='boolean')fail('invalid switches');const count=n.points?.length;if(!Number.isInteger(count)||count<2||count>8||n.points.some(p=>!Array.isArray(p)||p.length!==3||p.some(v=>!num(v,-10,10))))fail('use 2–8 finite spine handles');for(const [key,lo,hi]of [['widths',.03,8],['twists',-1440,1440]])if(n[key]?.length!==count||n[key].some(v=>!num(v,lo,hi)))fail('invalid '+key);for(const [k,lo,hi]of [['stretch',.1,5],['thickness',.05,5],['turn',-1440,1440],['lag',0,1],['spring',0,1]])if(!num(n[k],lo,hi))fail('invalid '+k);if(n.faces&&Object.entries(n.faces).some(([k,v])=>!['side','back'].includes(k)||typeof v!=='string'))fail('invalid turning artwork');}
export function validateNoodles(doc,nodes=doc.joints??doc.nodes,assets=[]){const ids=new Set(nodes.map(n=>n.id));for(const n of nodes){validateNoodle(n.noodle);for(const id of Object.values(n.noodle?.faces??{}))if(id&&!assets.some(a=>a.id===id))fail('missing turning artwork');if(n.skin){const s=n.skin;if(!Array.isArray(s.bones)||!s.bones.length||s.bones.length>32||new Set(s.bones.map(b=>b.id)).size!==s.bones.length||s.bones.some(b=>!ids.has(b.id)||b.id===n.id||!num(b.weight??1,.001,100)||b.bind?.length!==16||b.bind.some(v=>!Number.isFinite(v)))||s.owner?.length!==16||s.owner.some(v=>!Number.isFinite(v)))fail('invalid skeleton binding');}}
 for(const c of doc.clips){if(c.noodleTracks!==undefined&&(!Array.isArray(c.noodleTracks)||new Set(c.noodleTracks.map(t=>t.node)).size!==c.noodleTracks.length))fail('duplicate or invalid tracks');for(const t of c.noodleTracks??[]){if(!Array.isArray(t.keys)||t.keys.length>4096)fail('invalid keys');const n=nodes.find(n=>n.id===t.node);if(!n?.noodle)fail('keyed object has no deformer');let last=-1;for(const k of t.keys){if(!num(k.time,0,c.duration)||k.time<=last||!['linear','smooth','step'].includes(k.easing))fail('invalid keys');if(!k.value||['points','widths','twists','stretch','thickness','turn'].some(key=>k.value[key]===undefined))fail('incomplete pose key');validateNoodle({...n.noodle,...k.value});if(k.value.points.length!==n.noodle.points.length)fail('key topology differs');last=k.time;}}}
}
const mix=(a,b,t)=>Array.isArray(a)?a.map((v,i)=>mix(v,b[i],t)):a+(b-a)*t;
export function sampleNoodle(n,clip,id,time){if(!n)return null;const track=clip?.noodleTracks?.find(t=>t.node===id),duration=clip?.duration??1;time=clip?.loop?((time%duration)+duration)%duration:clamp(time,0,duration);
 const sample=t=>{t=clip?.loop?((t%duration)+duration)%duration:clamp(t,0,duration);let a={time:0,value:noodlePose(n),easing:'smooth'},b;for(const k of track?.keys??[]){if(k.time>t){b=k;break;}a=k;}if(!b)return a.value;const u=a.easing==='step'?0:easing(clamp((t-a.time)/(b.time-a.time)),a.easing);return Object.fromEntries(Object.keys(a.value).map(k=>[k,mix(a.value[k],b.value[k],u)]));};
 const out={...n,...structuredClone(sample(time))};
 // A finite, deterministic delayed response gives the same pose when scrubbing,
 // rendering out of order, or exporting. Successive handles trail progressively.
 if(n.lag>0&&track)for(let i=1;i<n.points.length;i++){const delay=n.lag*i/(n.points.length-1),a=sample(time-delay),b=sample(time-delay*1.65);out.points[i]=a.points[i].map((v,k)=>clamp(v+(v-b.points[i][k])*n.spring,-10,10));out.twists[i]=clamp(a.twists[i]+(a.twists[i]-b.twists[i])*n.spring,-1440,1440);out.widths[i]=clamp(a.widths[i]+(a.widths[i]-b.widths[i])*n.spring,.03,8);}
 return out;
}
export function applyNoodleCommand(project,c){const doc=c.dimension===3?project.scene3d:project,nodes=doc?.nodes??doc?.joints,n=nodes?.find(n=>n.id===c.node),clip=doc?.clips.find(v=>v.id===c.clip)??doc?.clips[0];if(!n||!clip)fail('select an object and clip');if(c.op==='noodle.remove'){delete n.noodle;for(const clip of doc.clips)clip.noodleTracks=(clip.noodleTracks??[]).filter(t=>t.node!==n.id);return n.id;}if(c.op==='noodle.bind'){if(c.dimension!==3)fail('use Bind Bones for 2D skeletons');if(c.binding)n.skin=structuredClone(c.binding);else delete n.skin;validateNoodles(doc,nodes,project.assets);return n.id;}
 const next={...structuredClone(n.noodle??noodleDefaults()),...structuredClone(c.values??{})};validateNoodle(next);
 if(c.op==='noodle.set'){n.noodle=next;validateNoodles(doc,nodes,project.assets);return n.id;}
 if(c.op!=='noodle.key')fail('unknown command');if(!n.noodle)n.noodle=noodleDefaults();if(!num(c.time,0,clip.duration))fail('key outside clip');clip.noodleTracks??=[];let t=clip.noodleTracks.find(t=>t.node===n.id);if(!t){t={node:n.id,keys:[]};if(c.time>0)t.keys.push({time:0,value:noodlePose(n.noodle),easing:'smooth'});clip.noodleTracks.push(t);}t.keys=t.keys.filter(k=>Math.abs(k.time-c.time)>1e-6);if(!c.remove)t.keys.push({time:c.time,value:noodlePose(next),easing:c.easing??'smooth'});t.keys.sort((a,b)=>a.time-b.time);validateNoodles(doc,nodes,project.assets);return n.id;
}

export function pruneNoodles(doc){const nodes=doc.nodes??doc.joints,ids=new Set(nodes.map(n=>n.id));for(const c of doc.clips)if(c.noodleTracks)c.noodleTracks=c.noodleTracks.filter(t=>ids.has(t.node));for(const n of nodes)if(n.skin){n.skin.bones=n.skin.bones.filter(b=>ids.has(b.id));if(!n.skin.bones.length)delete n.skin;}}
