import * as T from 'three';
import {SVGLoader} from 'three/addons/loaders/SVGLoader.js';
import {subdivideIndexed} from '../subdivision.js';
function flatten(path,tolerance){const pts=[];for(const curve of path.curves){const a=curve.getPoint(0),b=curve.getPoint(1);if(!pts.length)pts.push(a);const visit=(t0,p0,t1,p1,depth)=>{const chord=p1.clone().sub(p0),len=chord.length(),err=p=>len?Math.abs(chord.x*(p0.y-p.y)-(p0.x-p.x)*chord.y)/len:p.distanceTo(p0);const mid=curve.getPoint((t0+t1)/2),q=curve.getPoint(t0+(t1-t0)*.25),r=curve.getPoint(t0+(t1-t0)*.75);if(depth<14&&Math.max(err(mid),err(q),err(r))>tolerance){visit(t0,p0,(t0+t1)/2,mid,depth+1);visit((t0+t1)/2,mid,t1,p1,depth+1);}else pts.push(p1);};visit(0,a,1,b,0);}if(pts.length>1&&pts[0].distanceToSquared(pts.at(-1))<1e-10)pts.pop();return pts;}
function roleFor(color){const c=color.clone().convertLinearToSRGB(),max=Math.max(c.r,c.g,c.b);if(max<.12)return [3,1];if(c.r>.7&&c.g>.65&&c.b>.40)return [2,Math.min(1.1,max/.93)];if(c.r>c.b*1.4&&c.r>c.g*1.06){if(c.r>.7&&c.g>.67&&c.b>.40)return [2,Math.min(1.1,max/.93)];return [1,Math.min(1.1,max/.77)];}return [0,Math.min(1.35,max/.29)];}
export function createVectorGeometry(data,tolerance=.6,{front=0,iris=0,widthScale=2.3,irisWidth=2.06}={}){const pos=[],normals=[],uv=[],roles=[],tones=[],indices=[];const root=data.parsed.xml,box=(root.getAttribute('viewBox')||'0 0 '+root.getAttribute('width')+' '+root.getAttribute('height')).trim().split(/[ ,]+/).map(Number),width=parseFloat(root.getAttribute('width'))||box[2],height=parseFloat(root.getAttribute('height'))||box[3];let layer=0;
 for(const p of data.parsed.paths){if(p.userData.style.fill==='none')continue;const [role,tone]=roleFor(p.color);for(const shape of SVGLoader.createShapes(p)){const contour=flatten(shape,tolerance),holes=shape.holes.map(h=>flatten(h,tolerance));if(contour.length<3)continue;const tris=T.ShapeUtils.triangulateShape(contour,holes),verts=contour.concat(...holes),base=pos.length/3;for(const v of verts){const x=(v.x-box[0])/width,y=(v.y-box[1])/height;pos.push((x-.5)*(iris?irisWidth:widthScale),(.5-y)*(iris?irisWidth:widthScale),0);normals.push(0,0,1);uv.push(x,1-y);roles.push(role);tones.push(tone);}for(const tri of tris)indices.push(...tri.slice().reverse().map(i=>i+base));}layer++;}
 const geo=new T.BufferGeometry();for(const [key,array,size]of [['position',pos,3],['normal',normals,3],['uv',uv,2],['paintRole',roles,1],['paintTone',tones,1]])geo.setAttribute(key,new T.Float32BufferAttribute(array,size));geo.setIndex(indices);geo.computeBoundingSphere();return subdivideIndexed(geo,front||iris?.06:.11);
}
