import {multiply,inverse,point} from '../joint-transforms.js';
import {easing,easeNames} from '../fx/math.js';
import {normalizeWeights} from '../bone-binding/model.js';
import {triangulate,cross,at,gridMesh} from './geometry.js';
export * from './geometry.js';
export const MESH_COMMANDS=['mesh.create','mesh.remove','mesh.enabled','mesh.contour','mesh.vertex','mesh.addVertex','mesh.removeVertex','mesh.edge','mesh.generate','mesh.positions','mesh.key','mesh.bind','mesh.unbind','mesh.weights','mesh.paste'];
const fail=m=>{throw Error('Mesh: '+m);};
export const meshMatrix=s=>[s.width,0,0,s.height,-s.pivotX*s.width,-s.pivotY*s.height];
export function sampleMeshPositions(mesh,clip,joint,time){const keys=clip?.meshTracks?.find(t=>t.joint===joint)?.keys;if(!keys?.length)return [...mesh.positions];if(time<=keys[0].time)return [...keys[0].value];if(time>=keys.at(-1).time)return [...keys.at(-1).value];const i=keys.findIndex(k=>k.time>time),a=keys[i-1],b=keys[i],u=easing((time-a.time)/(b.time-a.time),a.easing,a.bezier);return a.value.map((v,i)=>v+(b.value[i]-v)*u);}
export function sampleMesh(joint,pose,clip,time){const mesh=joint.sprite?.mesh;if(!mesh?.enabled)return null;const positions=sampleMeshPositions(mesh,clip,joint.id,time),binding=mesh.binding;if(!binding)return positions;const toLocal=inverse(multiply(pose.get(joint.id).world,meshMatrix(joint.sprite))),matrices=new Map(binding.bones.map(b=>[b.joint,multiply(toLocal,multiply(pose.get(b.joint).world,multiply(inverse(b.bindWorld),binding.bindOwner)))]));return positions.flatMap((_,i)=>{if(i%2)return [];let x=0,y=0;for(const w of binding.weights[i/2]){const p=point(matrices.get(w.bone),{x:positions[i],y:positions[i+1]});x+=p.x*w.weight;y+=p.y*w.weight;}return[x,y];});}
export function bindMesh(joint,pose,bones,positions=joint.sprite.mesh.positions){if(!Array.isArray(bones)||!bones.length||bones.length>32||new Set(bones).size!==bones.length||bones.some(id=>!pose.has(id)))fail('choose 1–32 distinct bones');const bindOwner=multiply(pose.get(joint.id).world,meshMatrix(joint.sprite)),refs=bones.map(joint=>({joint,bindWorld:[...pose.get(joint).world]}));return{bindOwner,bones:refs,weights:Array.from({length:positions.length/2},(_,i)=>{const p=point(bindOwner,{x:positions[i*2],y:positions[i*2+1]}),near=refs.map(b=>({bone:b.joint,d:Math.hypot(p.x-b.bindWorld[4],p.y-b.bindWorld[5])})).sort((a,b)=>a.d-b.d).slice(0,2);return normalizeWeights(near[0].d<1e-8?[{bone:near[0].bone,weight:1}]:near.map(b=>({bone:b.bone,weight:1/b.d**2})),bones);})};}
const coords=(p,n)=>Array.isArray(p)&&p.length===n&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<=100);
export function validateMeshes(project){const ids=new Set(project.joints.map(j=>j.id));for(const j of project.joints){const m=j.sprite?.mesh;if(!m)continue;if(m.version!==1||typeof m.enabled!=='boolean')fail('invalid definition');if(j.sprite.boneBinding||j.sprite.crop||j.sprite.slicing?.enabled||j.bodyJoin?.enabled||project.procedural?.bindings?.some(b=>b.joint===j.id&&b.enabled!==false))fail('remove vector binding, crop, slicing, body joins or procedural sprite binding first');if(!coords(m.vertices,m.vertices?.length)||!coords(m.positions,m.vertices.length)||m.vertices.length%2||m.vertices.length<6||m.vertices.length>512)fail('invalid vertex positions');if(!Array.isArray(m.edges)||m.edges.length>512)fail('invalid forced edges');const expected=triangulate(m.vertices,m.contour,m.edges);if(!Array.isArray(m.triangles)||m.triangles.length%3||m.triangles.length>1536||m.triangles.length!==expected.length)fail('invalid triangles');const canonical=t=>Array.from({length:t.length/3},(_,i)=>t.slice(i*3,i*3+3).sort((a,b)=>a-b).join(':')).sort().join(';');if(canonical(m.triangles)!==canonical(expected))fail('regenerate triangles after editing topology');const seen=new Set();let area=0;const edgeSet=new Set();for(let i=0;i<m.triangles.length;i+=3){const t=m.triangles.slice(i,i+3);if(t.some(n=>!Number.isInteger(n)||n<0||n>=m.vertices.length/2)||new Set(t).size!==3)fail('invalid triangle index');const key=[...t].sort((a,b)=>a-b).join(':');if(seen.has(key))fail('duplicate triangle');seen.add(key);const a=cross(...t.map(i=>at(m.vertices,i)))/2;if(a<1e-10)fail('degenerate or reversed source triangle');area+=a;for(let k=0;k<3;k++)edgeSet.add([t[k],t[(k+1)%3]].sort((a,b)=>a-b).join(':'));}const polygonArea=Math.abs(m.contour.reduce((s,a,i)=>{const b=m.contour[(i+1)%m.contour.length];return s+m.vertices[a*2]*m.vertices[b*2+1]-m.vertices[b*2]*m.vertices[a*2+1];},0))/2;if(Math.abs(area-polygonArea)>1e-7)fail('triangles must cover the contour');
 const b=m.binding;if(b){const matrix=m=>Array.isArray(m)&&m.length===6&&m.every(Number.isFinite)&&Math.abs(m[0]*m[3]-m[1]*m[2])>1e-10;if(!matrix(b.bindOwner)||!Array.isArray(b.bones)||!b.bones.length||b.bones.length>32||new Set(b.bones.map(x=>x.joint)).size!==b.bones.length||b.bones.some(x=>!ids.has(x.joint)||!matrix(x.bindWorld))||!Array.isArray(b.weights)||b.weights.length!==m.vertices.length/2)fail('invalid bone binding');for(const ws of b.weights){if(!Array.isArray(ws)||ws.length>32)fail('invalid weights');normalizeWeights(ws,b.bones.map(x=>x.joint));if(Math.abs(ws.reduce((s,w)=>s+w.weight,0)-1)>1e-6)fail('weights must sum to 1');}}
 }
 for(const clip of project.clips){if(clip.meshTracks===undefined)continue;if(!Array.isArray(clip.meshTracks)||clip.meshTracks.length>project.joints.length)fail('invalid animation tracks');const seen=new Set();for(const t of clip.meshTracks){const mesh=project.joints.find(j=>j.id===t.joint)?.sprite?.mesh;if(!mesh||seen.has(t.joint)||!Array.isArray(t.keys)||t.keys.length>4096)fail('missing mesh or duplicate animation');seen.add(t.joint);let last=-1;for(const k of t.keys){if(!Number.isFinite(k.time)||k.time<0||k.time>clip.duration||k.time<=last||!coords(k.value,mesh.positions.length)||!easeNames.includes(k.easing))fail('invalid mesh key');if(k.bezier!==undefined&&(!Array.isArray(k.bezier)||k.bezier.length!==4||k.bezier.some(v=>!Number.isFinite(v))||k.bezier[0]<0||k.bezier[0]>1||k.bezier[2]<0||k.bezier[2]>1))fail('invalid Bezier easing');last=k.time;}}}return project;}
export function pruneMeshes(project){const ids=new Set(project.joints.map(j=>j.id));for(const j of project.joints){const b=j.sprite?.mesh?.binding;if(!b)continue;b.bones=b.bones.filter(b=>ids.has(b.joint));if(!b.bones.length){delete j.sprite.mesh.binding;continue;}const bones=b.bones.map(b=>b.joint);b.weights=b.weights.map(ws=>{const weights=ws.filter(w=>bones.includes(w.bone));return weights.some(w=>w.weight>0)?normalizeWeights(weights,bones):[{bone:bones[0],weight:1}];});}for(const c of project.clips)if(c.meshTracks)c.meshTracks=c.meshTracks.filter(t=>project.joints.find(j=>j.id===t.joint)?.sprite?.mesh);}
export function remapMeshes(joints,ids){for(const j of joints){const b=j.sprite?.mesh?.binding;if(!b)continue;for(const bone of b.bones)bone.joint=ids[bone.joint]??bone.joint;for(const ws of b.weights)for(const w of ws)w.bone=ids[w.bone]??w.bone;}}
