import {multiply,inverse,point} from '../joint-transforms.js';
import {sampleVector} from '../vector/model.js';
export const BONE_BINDING_COMMANDS=['boneBinding.bind','boneBinding.weights','boneBinding.unbind','boneBinding.enabled'];
const fail=m=>{throw Error('Bone binding: '+m);};
const matrixOK=m=>Array.isArray(m)&&m.length===6&&m.every(Number.isFinite)&&Math.abs(m[0]*m[3]-m[1]*m[2])>1e-10;
export function assetMatrix(sprite,vector){const [x,y,w,h]=vector.viewBox,sx=sprite.width/w,sy=sprite.height/h;return[sx,0,0,sy,-sprite.pivotX*sprite.width-x*sx,-sprite.pivotY*sprite.height-y*sy];}
export function normalizeWeights(weights,bones){const result=[],seen=new Set();for(const item of weights){if(!bones.includes(item.bone)||seen.has(item.bone)||!Number.isFinite(item.weight)||item.weight<0)fail('invalid bone weights');seen.add(item.bone);if(item.weight>0)result.push({bone:item.bone,weight:item.weight});}const total=result.reduce((n,w)=>n+w.weight,0);if(total<=0)fail('assign at least one nonzero weight');return result.map(w=>({...w,weight:w.weight/total}));}
export function bindVector(project,jointId,pose,boneIds,{shapes,influences=2}={}){const j=project.joints.find(j=>j.id===jointId),s=j?.sprite,v=project.assets.find(a=>a.id===s?.asset)?.vector;if(!v)fail('choose a sprite with editable SVG artwork');if(s.mesh||s.crop||s.slicing?.enabled||j.bodyJoin?.enabled||project.procedural?.bindings?.some(b=>b.joint===j.id&&b.enabled!==false))fail('remove mesh, crop, slicing, body joins or procedural binding before binding vector points');if(!boneIds.length||boneIds.length>32||new Set(boneIds).size!==boneIds.length||boneIds.some(id=>!pose.has(id)))fail('select 1–32 distinct joints');
 const owner=pose.get(jointId).world,bindAsset=multiply(owner,assetMatrix(s,v)),bones=boneIds.map(joint=>({joint,bindWorld:[...pose.get(joint).world]}));
 const bindings=v.shapes.filter(s=>!shapes||shapes.includes(s.id)).map(s=>({shape:s.id,commands:[...s.commands],weights:Array.from({length:s.points.length/2},(_,i)=>{const p=point(bindAsset,{x:s.points[i*2],y:s.points[i*2+1]}),near=bones.map(b=>({bone:b.joint,d:Math.hypot(p.x-b.bindWorld[4],p.y-b.bindWorld[5])})).sort((a,b)=>a.d-b.d).slice(0,Math.max(1,Math.min(4,influences)));return normalizeWeights(near[0].d<1e-7?[{bone:near[0].bone,weight:1}]:near.map(b=>({bone:b.bone,weight:1/(b.d*b.d)})),boneIds);})}));
 if(!bindings.length)fail('choose at least one path');return{enabled:true,bindAsset,bones,shapes:bindings};
}
export function validateBoneBindings(project){const ids=new Set(project.joints.map(j=>j.id));for(const j of project.joints){const b=j.sprite?.boneBinding;if(!b)continue;const v=project.assets.find(a=>a.id===j.sprite.asset)?.vector;if(!v||typeof b.enabled!=='boolean'||!matrixOK(b.bindAsset)||!Array.isArray(b.bones)||!b.bones.length||b.bones.length>32)fail('invalid binding on '+j.name);if(j.sprite.mesh||j.sprite.crop||j.sprite.slicing?.enabled||j.bodyJoin?.enabled||project.procedural?.bindings?.some(x=>x.joint===j.id&&x.enabled!==false))fail('vector binding cannot share a mesh, crop, slicing, body joins or procedural binding');const bones=new Set();for(const bone of b.bones){if(!ids.has(bone.joint)||bones.has(bone.joint)||!matrixOK(bone.bindWorld))fail('invalid or missing bone');bones.add(bone.joint);}if(!Array.isArray(b.shapes)||b.shapes.length>v.shapes.length)fail('invalid bound paths');const seen=new Set();for(const s of b.shapes){const shape=v.shapes.find(x=>x.id===s.shape);if(!shape||seen.has(s.shape)||!Array.isArray(s.weights)||s.weights.length!==shape.points.length/2||JSON.stringify(s.commands)!==JSON.stringify(shape.commands))fail('path topology changed; unbind it before adding/removing points');seen.add(s.shape);for(const weights of s.weights){if(!Array.isArray(weights)||weights.length<1||weights.length>32)fail('invalid vertex weights');const ws=new Set();let total=0;for(const w of weights){if(!bones.has(w.bone)||ws.has(w.bone)||!Number.isFinite(w.weight)||w.weight<0||w.weight>1)fail('invalid vertex influence');ws.add(w.bone);total+=w.weight;}if(Math.abs(total-1)>1e-6)fail('vertex weights must sum to 1');}}}return project;}
export function pruneBoneBindings(project){if(!project.joints)return;const ids=new Set(project.joints.map(j=>j.id));for(const j of project.joints){const b=j.sprite?.boneBinding;if(!b)continue;const v=project.assets.find(a=>a.id===j.sprite.asset)?.vector;if(!v){delete j.sprite.boneBinding;continue;}b.bones=b.bones.filter(b=>ids.has(b.joint));if(!b.bones.length){delete j.sprite.boneBinding;continue;}const bones=b.bones.map(b=>b.joint);b.shapes=b.shapes.filter(s=>v.shapes.some(x=>x.id===s.shape));for(const s of b.shapes)s.weights=s.weights.map(ws=>{const next=ws.filter(w=>bones.includes(w.bone)&&w.weight>0);return next.length?normalizeWeights(next,bones):[{bone:bones[0],weight:1}];});}}
// Skin vertices AND cubic control handles; the result remains editable vector
// geometry. Animation keys are sampled first, then each control point is skinned.
const frameCache=new WeakMap();
export function boundVector(vector,joint,pose,time=0){const b=joint.sprite?.boneBinding;if(!b?.enabled||!pose?.has(joint.id))return null;
 let cache=frameCache.get(b);// Authored vectors and weights may be edited in place; resample without discarding the reusable render surface.
 const s=joint.sprite,toAsset=inverse(multiply(pose.get(joint.id).world,assetMatrix(s,vector))),bones=new Map(b.bones.map(bone=>[bone.joint,multiply(toAsset,multiply(pose.get(bone.joint).world,multiply(inverse(bone.bindWorld),b.bindAsset)))])),bindings=new Map(b.shapes.map(s=>[s.shape,s]));
 const shapes=sampleVector(vector,time).map(shape=>{const binding=bindings.get(shape.id);if(!binding)return shape;const points=[...shape.points];for(let i=0;i<points.length;i+=2){let x=0,y=0;for(const influence of binding.weights[i/2]){const p=point(bones.get(influence.bone),{x:shape.points[i],y:shape.points[i+1]});x+=p.x*influence.weight;y+=p.y*influence.weight;}points[i]=x;points[i+1]=y;}return{...shape,points};});
 const [vx,vy,vw,vh]=vector.viewBox;let minX=vx,minY=vy,maxX=vx+vw,maxY=vy+vh;for(const shape of shapes)if(!shape.hidden){const padding=shape.strokeWidth/2+1;for(let i=0;i<shape.points.length;i+=2){minX=Math.min(minX,shape.points[i]-padding);minY=Math.min(minY,shape.points[i+1]-padding);maxX=Math.max(maxX,shape.points[i]+padding);maxY=Math.max(maxY,shape.points[i+1]+padding);}}
 const width=maxX-minX,height=maxY-minY,expanded={...s,width:s.width*width/vw,height:s.height*height/vh,pivotX:(vx+s.pivotX*vw-minX)/width,pivotY:(vy+s.pivotY*vh-minY)/height};delete expanded.boneBinding;
 const sampled={...vector,viewBox:[minX,minY,width,height],shapes,tracks:[],boil:undefined,boundFrame:(cache?.result.vector.boundFrame??0)+1};if(cache?.source===vector){Object.assign(cache.result.vector,sampled);cache.result.sprite=expanded;}else{cache={source:vector,result:{vector:sampled,sprite:expanded}};frameCache.set(b,cache);}return cache.result;
}

export function remapBoneBindings(joints,ids){for(const j of joints){const b=j.sprite?.boneBinding;if(!b)continue;for(const bone of b.bones)bone.joint=ids[bone.joint]??bone.joint;for(const shape of b.shapes)for(const weights of shape.weights)for(const influence of weights)influence.bone=ids[influence.bone]??influence.bone;}}
