import {orderChains} from './kinematics.js';
import {orderAttachments} from './attachments.js';
/** Serializable, renderer-independent 2D procedural rigs. Units are pixels, seconds. */
export const PROCEDURAL_VERSION = 1;
export const emptyProcedural = () => ({version:1, gravity:[0,300], damping:3, iterations:16, particles:[], distances:[], bends:[], areas:[], rigid:[], chains:[], drivers:[], colliders:[], surfaces:[], bindings:[], connections:[], gaits:[], supports:[], attachments:[]});
const fail = message => { throw Error('Procedural: '+message); };
const number = (v,min,max,label) => {if(!Number.isFinite(v)||v<min||v>max)fail(label+' is out of range');};
const list = (v,max,label) => {if(!Array.isArray(v)||v.length>max)fail(label+' must be an array of at most '+max);};
const vec = (v,label) => {list(v,2,label);if(v.length!==2)fail(label+' needs X and Y');v.forEach(x=>number(x,-1e6,1e6,label));};
const id = v => typeof v==='string' && /^[a-zA-Z0-9_-]{1,100}$/.test(v);
const colour = v => v==='none'||typeof v==='string'&&/^#[a-fA-F0-9]{6}$/.test(v);
export function validateProcedural(p,joints=[]){
 if(p===undefined)return;
 if(!p||p.version!==1)fail('unsupported version');
 vec(p.gravity,'gravity');number(p.damping,0,100,'damping');number(p.iterations,1,80,'iterations');if(!Number.isInteger(p.iterations))fail('iterations must be integer');
 for(const key of ['particles','distances','bends','areas','rigid','chains','drivers','colliders','surfaces'])list(p[key],key==='particles'?512:1024,key);
 const ids=new Set(),jointIds=new Set(joints.map(j=>j.id));
 for(const a of p.particles){if(!id(a.id)||ids.has(a.id))fail('particle IDs must be unique');ids.add(a.id);vec(a.position,'position');number(a.mass,0,10000,'mass');number(a.radius,0,1000,'radius');if(a.joint!==undefined&&!jointIds.has(a.joint))fail('missing joint '+a.joint);if(a.owner!==undefined&&!jointIds.has(a.owner))fail('missing owner '+a.owner);if(a.gravity!==undefined)vec(a.gravity,'particle gravity');if(a.damping!==undefined)number(a.damping,0,100,'particle damping');if(a.offset!==undefined)vec(a.offset,'joint offset');}
 const refs=(values,min=2)=>{list(values,512,'particle references');if(values.length<min||new Set(values).size!==values.length||values.some(n=>!ids.has(n)))fail('invalid particle references');};
 const strength = c => number(c.stiffness??1,0,1,'stiffness');
 for(const c of p.distances){refs([c.a,c.b]);number(c.length,.001,1e6,'distance length');strength(c);}
 for(const c of p.bends){refs([c.a,c.b,c.c]);number(c.angle,-Math.PI,Math.PI,'rest bend');number(c.limit,0,Math.PI,'bend limit');strength(c);}
 for(const c of p.areas){refs(c.particles,3);number(c.area,-1e10,1e10,'rest area');strength(c);}
 for(const c of p.rigid){refs(c.particles,2);strength(c);}
 const targets=t=>{if(typeof t==='string'){if(!ids.has(t))fail('missing target '+t);}else vec(t,'target');};
 for(const c of p.chains){refs(c.particles);if(c.id!==undefined&&!id(c.id))fail('invalid chain ID');if(c.placement!==undefined&&!['terrain','target'].includes(c.placement))fail('unknown step placement');if(!['reach','follow','step'].includes(c.mode))fail('unknown chain mode');targets(c.target);if(c.lengths===undefined)for(let i=1;i<c.particles.length;i++){const a=p.particles.find(p=>p.id===c.particles[i-1]).position,b=p.particles.find(p=>p.id===c.particles[i]).position;if(Math.hypot(a[0]-b[0],a[1]-b[1])<.001)fail('chain points must have nonzero rest spacing');}if(c.lengths!==undefined){list(c.lengths,511,'chain lengths');if(c.lengths.length!==c.particles.length-1)fail('chain lengths mismatch');c.lengths.forEach(x=>number(x,.001,1e6,'chain length'));}number(c.bendLimit??Math.PI,0,Math.PI,'chain bend limit');if(c.mode==='step'){number(c.overshoot??0,0,2,'step overshoot');number(c.stepDistance??25,1,1000,'step distance');number(c.stepHeight??20,0,1000,'step height');number(c.stepDuration??.2,.02,10,'step duration');number(c.reach??200,1,1e5,'contact search reach');vec(c.direction??[0,1],'contact direction');if(Math.hypot(...(c.direction??[0,1]))<1e-8)fail('contact direction is zero');if(c.group!==undefined&&!id(c.group))fail('invalid step group');}}
 list(p.impulses??[],1024,'impulses');const impulseIds=new Set();for(const e of p.impulses??[]){if(!id(e.id)||impulseIds.has(e.id))fail('invalid impulse ID');impulseIds.add(e.id);refs(e.particles,1);vec(e.velocity,'impulse velocity');number(e.time,0,120,'impulse time');if(e.particles.some(id=>{const point=p.particles.find(p=>p.id===id);return point.mass===0||point.joint||p.drivers.some(d=>d.particle===id)||(p.attachments??[]).some(a=>a.particle===id)||p.chains.some(c=>c.particles.slice(c.mode==='follow'?0:1).includes(id));}))fail('impulse needs free dynamic points');}
 const driven=new Set();for(const d of p.drivers){if(!ids.has(d.particle)||driven.has(d.particle))fail('missing or duplicate driver');driven.add(d.particle);if(!['orbit','wave','target'].includes(d.type))fail('unknown driver');vec(d.origin,'driver origin');vec(d.amplitude,'driver amplitude');number(d.frequency,0,20,'frequency');number(d.phase??0,-10000,10000,'phase');}
 for(const c of p.colliders){if(c.type==='segment'){vec(c.a,'segment start');vec(c.b,'segment end');if(Math.hypot(c.b[0]-c.a[0],c.b[1]-c.a[1])<.001)fail('empty segment');}else if(c.type==='circle'){vec(c.center,'circle center');number(c.radius,.1,1e5,'collider radius');}else fail('unknown collider');number(c.friction??.5,0,1,'friction');number(c.bounce??0,0,1,'bounce');}
 const surfaceIds=new Set();for(const s of p.surfaces){if(!id(s.id)||surfaceIds.has(s.id))fail('surface IDs must be unique');surfaceIds.add(s.id);if(typeof s.name!=='string'||s.name.length>200)fail('surface name');number(s.layer,-10000,10000,'surface layer');number(s.opacity??1,0,1,'surface opacity');if(!colour(s.fill)||!colour(s.stroke))fail('surface colours must be hex or none');number(s.strokeWidth,0,1000,'stroke width');if(!['round','ink'].includes(s.outline))fail('outline style');number(s.smoothing??.5,0,1,'ink smoothing');number(s.thinning??0,-1,1,'ink thinning');list(s.shapes,128,'surface shapes');for(const shape of s.shapes){if(!['tube','polygon','discs'].includes(shape.type))fail('unknown surface shape');refs(shape.particles,shape.type==='polygon'?3:shape.type==='tube'?2:1);if(shape.radii){list(shape.radii,512,'radii');if(shape.radii.length!==shape.particles.length)fail('radius count mismatch');shape.radii.forEach(x=>number(x,.01,1000,'surface radius'));}number(shape.curve??0,0,1,'surface curvature');if(shape.type==='discs'&&shape.curve)fail('curvature requires a loop or tube');if(shape.operation!==undefined&&!['add','subtract'].includes(shape.operation))fail('unknown shape operation');}}
 const bound=new Set();list(p.bindings??[],256,'sprite bindings');for(const b of p.bindings??[]){if(!jointIds.has(b.joint)||bound.has(b.joint))fail('missing or duplicate bound joint');bound.add(b.joint);refs(b.particles,1);if(!['rigid','soft'].includes(b.mode))fail('unknown sprite binding');number(b.strength??1,0,1,'binding strength');list(b.bindMatrix,6,'bind matrix');if(b.bindMatrix.length!==6)fail('bind matrix length');b.bindMatrix.forEach(v=>number(v,-1e6,1e6,'bind matrix'));if(Math.abs(b.bindMatrix[0]*b.bindMatrix[3]-b.bindMatrix[1]*b.bindMatrix[2])<1e-8)fail('singular bind matrix');list(b.rest,512,'bind positions');if(b.rest.length!==b.particles.length)fail('bind positions mismatch');b.rest.forEach(v=>vec(v,'bind position'));}

 const connectionIds=new Set();list(p.connections??[],256,'outline connections');for(const c of p.connections??[]){if(!id(c.id)||connectionIds.has(c.id))fail('connection IDs must be unique');connectionIds.add(c.id);if(!joints.find(j=>j.id===c.joint)?.sprite||!surfaceIds.has(c.surface)||!ids.has(c.particle))fail('missing outline connection piece, surface or point');number(c.radius,1,1000,'outline connection radius');if(c.enabled!==undefined&&typeof c.enabled!=='boolean')fail('connection enabled must be boolean');}
 const attached=new Set(),attachmentIds=new Set();list(p.attachments??[],256,'attachments');
 for(const a of p.attachments??[]){
  if(!id(a.id)||attachmentIds.has(a.id))fail('invalid attachment ID');attachmentIds.add(a.id);
  if(!ids.has(a.particle)||attached.has(a.particle))fail('missing or duplicate attached point');attached.add(a.particle);refs(a.sources,1);
  if(a.sources.includes(a.particle))fail('attachment cannot follow itself');
  if(a.weights!==undefined){list(a.weights,512,'attachment weights');if(a.weights.length!==a.sources.length)fail('attachment weight count');a.weights.forEach(w=>number(w,0,10000,'attachment weight'));if(a.weights.reduce((s,w)=>s+w,0)<=0)fail('attachment weights must have a positive sum');}
  if(a.offset!==undefined)vec(a.offset,'attachment offset');if(a.orient!==undefined){refs(a.orient,2);if(a.orient.length!==2||a.orient.includes(a.particle))fail('attachment orientation needs two other points');}
  if(a.bend!==undefined){const b=a.bend;if(!b||typeof b!=='object')fail('invalid bend response');refs(b.particles,3);if(b.particles.includes(a.particle))fail('bend response cannot measure its output');vec(b.scale,'bend offset scale');number(b.limit,0,Math.PI*512,'bend response limit');if(b.absolute!==undefined&&typeof b.absolute!=='boolean')fail('absolute bend must be boolean');}
  if(driven.has(a.particle)||p.particles.find(v=>v.id===a.particle).joint)fail('attached point cannot also have a driver or puppet anchor');
  if(p.chains.some(c=>c.particles.slice(c.mode==='follow'?0:1).includes(a.particle)))fail('attached point cannot also be a chain output');
 }
 orderAttachments(p.attachments);orderChains(p);
 const stepping=p.chains.filter(c=>c.mode==='step'),chainKeys=stepping.map(c=>c.id??c.particles[0]);
 const chainRefs=values=>{list(values,512,'step chain references');if(!values.length||new Set(values).size!==values.length||values.some(k=>chainKeys.filter(id=>id===k).length!==1))fail('step chain references must identify unique stepping chains');};
 const gaitIds=new Set(),scheduled=new Set();list(p.gaits??[],128,'gaits');for(const g of p.gaits??[]){if(!id(g.id)||gaitIds.has(g.id))fail('invalid gait ID');gaitIds.add(g.id);list(g.groups,64,'gait groups');if(!g.groups.length)fail('gait needs groups');for(const group of g.groups){chainRefs(group);for(const key of group){if(scheduled.has(key))fail('a step chain can belong to one gait group');scheduled.add(key);}}}
 const supportIds=new Set(),supported=new Set();list(p.supports??[],128,'body supports');for(const b of p.supports??[]){if(!id(b.id)||supportIds.has(b.id))fail('invalid support ID');supportIds.add(b.id);refs(b.particles,1);chainRefs(b.feet);vec(b.direction??[0,1],'support direction');if(Math.hypot(...(b.direction??[0,1]))<1e-8)fail('support direction is zero');number(b.height,0,10000,'body height');number(b.maxOffset??100,0,10000,'support travel');number(b.maxTilt??.6,0,Math.PI,'support tilt limit');number(b.tilt??1,0,1,'support tilt');number(b.response??10,.01,100,'support response');for(const key of b.particles){const point=p.particles.find(p=>p.id===key);if(supported.has(key))fail('body point can belong to one support');supported.add(key);if(point.mass>0&&!point.joint&&!driven.has(key))fail('body support points must be pinned, anchored or driven');}}

 return p;
}
export function signedArea(points){let a=0;for(let i=0;i<points.length;i++){const p=points[i],q=points[(i+1)%points.length];a+=p[0]*q[1]-p[1]*q[0];}return a/2;}
