export const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const lerp=(a,b,t)=>a+(b-a)*t;
export function random(seed){let s=(seed|0)||1;return()=>{s=(s+0x6D2B79F5)|0;let t=Math.imul(s^s>>>15,1|s);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296;};}
export function hash(...values){let h=2166136261;for(const text of values.map(String))for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return h>>>0;}
export const easeNames=['linear','smooth','step','in-quad','out-quad','in-out-quad','in-cubic','out-cubic','in-out-cubic','in-sine','out-sine','in-out-sine','in-expo','out-expo','in-circ','out-circ','out-back','out-elastic','out-bounce','bezier'];
export function easing(t,name='linear',bezier=[.25,.1,.25,1]){
 t=clamp(t);const bounce=x=>{const n=7.5625,d=2.75;if(x<1/d)return n*x*x;if(x<2/d)return n*(x-=1.5/d)*x+.75;if(x<2.5/d)return n*(x-=2.25/d)*x+.9375;return n*(x-=2.625/d)*x+.984375;};
 switch(name){case'smooth':return t*t*(3-2*t);case'step':return t===1?1:0;case'in-quad':return t*t;case'out-quad':return 1-(1-t)**2;case'in-out-quad':return t<.5?2*t*t:1-(-2*t+2)**2/2;case'in-cubic':return t*t*t;case'out-cubic':return 1-(1-t)**3;case'in-out-cubic':return t<.5?4*t*t*t:1-(-2*t+2)**3/2;case'in-sine':return 1-Math.cos(t*Math.PI/2);case'out-sine':return Math.sin(t*Math.PI/2);case'in-out-sine':return(1-Math.cos(Math.PI*t))/2;case'in-expo':return t===0?0:2**(10*t-10);case'out-expo':return t===1?1:1-2**(-10*t);case'in-circ':return 1-Math.sqrt(1-t*t);case'out-circ':return Math.sqrt(1-(t-1)**2);case'out-back':return 1+2.70158*(t-1)**3+1.70158*(t-1)**2;case'out-elastic':return t===0||t===1?t:2**(-10*t)*Math.sin((t*10-.75)*(2*Math.PI/3))+1;case'out-bounce':return bounce(t);case'bezier':{const [x1,y1,x2,y2]=bezier,f=(s,a,b)=>3*(1-s)**2*s*a+3*(1-s)*s*s*b+s**3;let lo=0,hi=1;for(let i=0;i<22;i++){const m=(lo+hi)/2;if(f(m,x1,x2)<t)lo=m;else hi=m;}return f((lo+hi)/2,y1,y2);}default:return t;}
}
export function curve(points,t,fallback=0){if(!points?.length)return fallback;if(t<=points[0].time)return points[0].value;if(t>=points.at(-1).time)return points.at(-1).value;const i=points.findIndex(p=>p.time>t),a=points[i-1],b=points[i];return lerp(a.value,b.value,easing((t-a.time)/(b.time-a.time),a.easing,a.bezier));}
export function parameter(value,t,fallback=0){return Array.isArray(value)?curve(value,t,fallback):typeof value==='number'?value:fallback;}
export function pathAt(points,t,closed=false){if(!points?.length)return{x:0,y:0};if(points.length===1)return{...points[0]};t=closed?((t%1)+1)%1:clamp(t);const total=closed?points.length:points.length-1,u=t*total,i=Math.min(total-1,Math.floor(u)),a=points[i],b=points[(i+1)%points.length],s=u-i;return{x:lerp(a.x,b.x,s),y:lerp(a.y,b.y,s)};}
export function rgb(hex){const s=(hex??'#ffffff').replace('#','');return s.length===3?[...s].map(c=>parseInt(c+c,16)):[0,2,4].map(i=>parseInt(s.slice(i,i+2),16)||0);}
export function colorAt(colors,t){if(!colors?.length)return[255,255,255];const u=clamp(t)*(colors.length-1),i=Math.min(colors.length-1,Math.floor(u)),a=rgb(colors[i]),b=rgb(colors[Math.min(colors.length-1,i+1)]);return a.map((v,k)=>Math.round(lerp(v,b[k],u-i)));}
export function paletteParse(text){let lines=text.trim().split(/\r?\n/);if(lines[0]==='JASC-PAL')lines=lines.slice(3);const result=[];for(const line of lines){const hex=line.match(/#[0-9a-f]{6}\b/ig);if(hex)result.push(...hex);else{const n=line.trim().split(/[ ,]+/).slice(0,3).map(Number);if(n.length===3&&n.every(v=>Number.isFinite(v)&&v>=0&&v<=255))result.push('#'+n.map(v=>Math.round(v).toString(16).padStart(2,'0')).join(''));}}return [...new Set(result)].slice(0,256);}
