import {clamp,lerp,easing,random,hash} from './math.js';
export const CUE_TYPES={sound:{label:'Sound',duration:.5,amount:1},'sprite-flash':{label:'Sprite flash',duration:.18,amount:.85},freeze:{label:'Freeze / hit-stop',duration:.045,amount:0},slow:{label:'Slow motion',duration:.35,amount:.25},shake:{label:'Screen shake',duration:.22,amount:8},flash:{label:'Screen flash',duration:.18,amount:.65},zoom:{label:'Camera punch',duration:.25,amount:.12},pan:{label:'Camera move',duration:.4,amount:40},fade:{label:'Fade',duration:.5,amount:1},letterbox:{label:'Letterbox',duration:1,amount:.12},impact:{label:'Impact frame',duration:.04,amount:1}};
export function cue(id,type,time=0){const d=CUE_TYPES[type];if(!d)throw Error('Unknown presentation cue '+type);return{id,type,time,duration:d.duration,amount:d.amount,color:type==='impact'?'#111425':'#ffe3ad',frequency:28,rotation:1.5,damping:4,x:1,y:1,easing:'out-cubic',seed:1,hold:false};}
export function animationTime(clip,time){const cues=(clip?.cues??[]).filter(c=>c.enabled!==false&&['freeze','slow'].includes(c.type)),points=[0,time];for(const c of cues){if(c.time>0&&c.time<time)points.push(c.time);const end=c.time+c.duration;if(end>0&&end<time)points.push(end);}points.sort((a,b)=>a-b);let result=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],mid=(a+b)/2;let speed=1;for(const c of cues)if(mid>=c.time&&mid<c.time+c.duration)speed*=c.type==='freeze'?0:clamp(c.amount,0,4);result+=(b-a)*speed;}return Math.max(0,result);}
export function presentationAt(clip,time){const state={time,animationTime:animationTime(clip,time),x:0,y:0,rotation:0,scale:1,overlays:[],letterbox:0};for(const c of clip?.cues??[]){if(c.enabled===false||time<c.time)continue;const age=time-c.time,u=clamp(age/c.duration);if(age>=c.duration&&!c.hold)continue;const decay=Math.exp(-u*(c.damping??4))*(1-u),phase=age*(c.frequency??28);
 if(c.type==='shake'){const r=random(hash(c.seed,c.id,Math.floor(phase))),next=random(hash(c.seed,c.id,Math.floor(phase)+1)),mix=easing(phase%1,'smooth');state.x+=lerp(r()*2-1,next()*2-1,mix)*c.amount*decay*(c.x??1);state.y+=lerp(r()*2-1,next()*2-1,mix)*c.amount*decay*(c.y??1);state.rotation+=(r()*2-1)*(c.rotation??1.5)*decay;}
 if(c.type==='zoom')state.scale*=1+c.amount*(c.hold?easing(u,c.easing):Math.sin(u*Math.PI)*Math.exp(-u*2));
 if(c.type==='pan'){const amount=easing(u,c.easing)*c.amount;state.x+=amount*(c.x??1);state.y+=amount*(c.y??0);}
 if(c.type==='flash')state.overlays.push({color:c.color,opacity:c.amount*(c.profile==='lightning'?Math.sin(Math.min(1,age/.48)*Math.PI)*Math.exp(-age*3):1-easing(u,'smooth')),blend:'screen'});
 if(c.type==='impact')state.overlays.push({color:c.color,opacity:c.amount,blend:'difference'});
 if(c.type==='fade')state.overlays.push({color:c.color,opacity:c.amount*easing(u,c.easing),blend:'source-over'});
 if(c.type==='letterbox')state.letterbox=Math.max(state.letterbox,c.amount*(c.hold?easing(u,c.easing):Math.sin(u*Math.PI)));
 }return state;}
export function presentationPreset(name,time=.5){const defs=name==='heavy-impact'?[['freeze',.075,0],['shake',.3,12],['flash',.18,.75],['zoom',.25,.1]]:name==='contact-impact'?[['freeze',.045,0],['shake',.075,2],['sprite-flash',.18,.85]]:name==='lightning'?[['flash',.48,.45],['shake',.25,3]]:name==='discovery'?[['flash',.22,.35],['zoom',.6,.08]]:[['slow',.5,.2],['zoom',.5,.08]];return defs.map(([type,duration,amount],i)=>({...cue(name+'-'+i,type,time),duration,amount,...(name==='contact-impact'?{profile:'contact'}:name==='lightning'?{profile:'lightning'}:{})}));}
export function validateCues(clip){if(clip.cues===undefined)return;if(!Array.isArray(clip.cues)||clip.cues.length>200)throw Error('Invalid presentation cue list');const ids=new Set();for(const c of clip.cues){if(!CUE_TYPES[c.type]||!c.id||ids.has(c.id))throw Error('Invalid or duplicate presentation cue');ids.add(c.id);for(const k of ['time','duration','amount'])if(!Number.isFinite(c[k]))throw Error('Invalid presentation '+k);if(c.type==='slow'&&(c.amount<0||c.amount>4))throw Error('Slow motion speed must be 0–4');if(c.type==='zoom'&&c.amount<=-1)throw Error('Camera scale must remain positive');if(['flash','sprite-flash','fade','impact','letterbox'].includes(c.type)&&(c.amount<0||c.amount>1))throw Error('Opacity / letterbox must be 0–1');if(c.time<0||c.time>clip.duration||c.duration<=0||c.duration>120)throw Error('Presentation cue is outside the timeline');}}

export function presentationTime(clip,sourceTime){if(!clip?.cues?.some(c=>c.enabled!==false&&['freeze','slow'].includes(c.type)))return sourceTime;let lo=0,hi=clip.duration;for(let i=0;i<40;i++){const mid=(lo+hi)/2;if(animationTime(clip,mid)<sourceTime-1e-8)lo=mid;else hi=mid;}return (lo+hi)/2;}
