import {boilShape} from '../../illustration/contours.js';
import {validateBezier} from '../authoring/easing.js';
import {easing} from '../fx/math.js';
import {trimStroke,TRIM_DEFAULTS} from './trim.js';
export {trimStroke,TRIM_DEFAULTS};
export {samplePath} from './trim.js';
export const VECTOR_CHANNELS=['fill','stroke','opacity','strokeWidth','points',...Object.keys(TRIM_DEFAULTS)];
export const vectorValue=(shape,channel)=>shape[channel]??TRIM_DEFAULTS[channel];
export const hexRGB=c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16));
export const rgbHex=c=>'#'+c.map(x=>Math.round(Math.max(0,Math.min(255,x))).toString(16).padStart(2,'0')).join('');
export function mixColor(a,b,t){if(a==='none'||b==='none')return t<1?a:b;const x=hexRGB(a),y=hexRGB(b);return rgbHex(x.map((v,i)=>v+(y[i]-v)*t));}
export function sampleKeys(keys,time,base){if(!keys?.length)return base;if(time<keys[0].time)return base;let a=keys[0],b;for(let i=1;i<keys.length;i++){if(keys[i].time>time){b=keys[i];break;}a=keys[i];}if(!b)return a.value;const t=easing((time-a.time)/(b.time-a.time),a.easing??'smooth',a.bezier);if(Array.isArray(a.value))return a.value.map((v,i)=>v+(b.value[i]-v)*t);if(typeof a.value==='number')return a.value+(b.value-a.value)*t;return mixColor(a.value,b.value,t);}
export function vectorTime(v,t){return v.loop?((t%v.duration)+v.duration)%v.duration:Math.max(0,Math.min(v.duration,t));}
export function sampleVector(v,t=0){const at=vectorTime(v,t),shapes=new Map(v.shapes.map(s=>[s.id,s]));for(const track of v.tracks??[]){const shape=shapes.get(track.shape);shapes.set(shape.id,{...shape,[track.channel]:sampleKeys(track.keys,at,vectorValue(shape,track.channel))});}return v.shapes.map(s=>{const out=shapes.get(s.id);if(out!==s){out.opacity=Math.max(0,Math.min(1,out.opacity));out.strokeWidth=Math.max(0,out.strokeWidth);for(const channel of ['trimStart','trimEnd'])if(out[channel]!==undefined)out[channel]=Math.max(0,Math.min(1,out[channel]));}return boilShape(out,at,v.boil);});}
export function paintColor(p,v){return typeof p==='string'?p:p?.swatch?v.swatches.find(s=>s.id===p.swatch)?.color??'#000000':'#000000';}
export function pathData(s){let index=0;return s.commands.map(c=>{const count={M:2,L:2,C:6,Z:0}[c],values=s.points.slice(index,index+count);index+=count;return c+values.map(x=>Number(x.toFixed(5))).join(' ');}).join(' ');}
export function anchors(s){let offset=0,start=null,previous=null;const result=[];for(let command=0;command<s.commands.length;command++){const type=s.commands[command],size={M:2,L:2,C:6,Z:0}[type];if(type==='Z'){if(previous&&start&&previous!==start&&Math.hypot(previous.x-start.x,previous.y-start.y)<1e-7){start.incoming=previous.incoming;start.aliases=[previous.index];result.splice(result.indexOf(previous),1);}previous=start;continue;}const index=offset+size-2,anchor={index,command,x:s.points[index],y:s.points[index+1],incoming:type==='C'?offset+2:null,outgoing:null};if(type==='M')start=anchor;if(type==='C'&&previous)previous.outgoing=offset;result.push(anchor);previous=anchor;offset+=size;}return result;}
export function movePoint(shape,index,dx,dy,{handle=false,mirror=false}={}){const s=structuredClone(shape),a=anchors(s),anchor=a.find(a=>a.index===index);s.points[index]+=dx;s.points[index+1]+=dy;if(anchor&&!handle){for(const i of anchor.aliases??[]){s.points[i]+=dx;s.points[i+1]+=dy;}for(const i of [anchor.incoming,anchor.outgoing])if(i!==null){s.points[i]+=dx;s.points[i+1]+=dy;}}else if(mirror){const owner=a.find(a=>a.incoming===index||a.outgoing===index);if(owner){const other=owner.incoming===index?owner.outgoing:owner.incoming;if(other!==null){s.points[other]=2*owner.x-s.points[index];s.points[other+1]=2*owner.y-s.points[index+1];}}}return s;}
export function transformShape(s,{dx=0,dy=0,sx=1,sy=1,angle=0,cx=0,cy=0}={}){const p=s.points.slice(),c=Math.cos(angle),n=Math.sin(angle);for(let i=0;i<p.length;i+=2){const x=(p[i]-cx)*sx,y=(p[i+1]-cy)*sy;p[i]=cx+x*c-y*n+dx;p[i+1]=cy+x*n+y*c+dy;}return {...s,points:p};}
export function shapeBounds(s){let x=Infinity,y=Infinity,right=-Infinity,bottom=-Infinity;for(let i=0;i<s.points.length;i+=2){x=Math.min(x,s.points[i]);y=Math.min(y,s.points[i+1]);right=Math.max(right,s.points[i]);bottom=Math.max(bottom,s.points[i+1]);}return{x,y,width:right-x,height:bottom-y};}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
// Clip sources contribute geometry, independent of their paint, visibility or own clips.
// Multiple clips intersect. Outside clips use the artboard plus an even-odd hole.
export function vectorClipGeometry(v, source, clip) {
 const d=pathData(source);
 if(!clip.inverse)return {d,rule:clip.rule??'nonzero'};
 const [x,y,w,h]=v.viewBox;
 return {d:`M${x} ${y} h${w} v${h} h${-w} Z ${d}`,rule:'evenodd'};
}
export function svgText(v,time=0){
 let defs='';
 const paint=(p,id)=>{if(!p?.type)return paintColor(p,v);const radial=p.type==='radial',tag=radial?'radialGradient':'linearGradient',attributes=radial?`cx="${p.x1}" cy="${p.y1}" r="${p.x2}"`:`x1="${p.x1}" y1="${p.y1}" x2="${p.x2}" y2="${p.y2}"`;defs+=`<${tag} id="${id}" gradientUnits="${p.units??'objectBoundingBox'}" ${attributes}>${p.stops.map(s=>`<stop offset="${s.offset}" stop-color="${s.color}" stop-opacity="${s.opacity??1}"/>`).join('')}</${tag}>`;return'url(#'+id+')';};
 const shapes=sampleVector(v,time),byId=new Map(shapes.map(s=>[s.id,s])),clips=new Map();
 const body=shapes.filter(s=>!s.hidden).map(s=>{
  const separateStroke=s.trimMode!==undefined,fill=paint(s.fill,'f'+s.id),stroke=paint(s.stroke,'s'+s.id);
  const style=`stroke-width="${s.strokeWidth}" fill-rule="${s.fillRule??'nonzero'}" stroke-linecap="${s.lineCap??'round'}" stroke-linejoin="${s.lineJoin??'round'}" opacity="${s.opacity}"`;
  const trim=s.trimMode!==undefined?` data-trim-mode="${s.trimMode}" data-trim-start="${s.trimStart??0}" data-trim-end="${s.trimEnd??1}" data-trim-offset="${s.trimOffset??0}" data-trim-stroke="${esc(stroke)}"`:'';
  let path=`<path data-vector-id="${esc(s.id)}" data-name="${esc(s.name)}" data-ink-role="${esc(s.role??'literal')}" d="${pathData(s)}" fill="${fill}" stroke="${separateStroke?'none':stroke}" ${style}${trim}/>`;
  if(separateStroke&&s.stroke!=='none'&&s.strokeWidth>0){
   // Trimming must not squeeze a gradient into the shortened stroke's bounds.
   let strokePaint=stroke;if(s.stroke?.type&&s.stroke.units==='objectBoundingBox'){const b=shapeBounds(s),p=s.stroke;strokePaint=paint({...p,units:'userSpaceOnUse',x1:b.x+p.x1*b.width,y1:b.y+p.y1*b.height,x2:p.type==='radial'?p.x2*Math.max(b.width,b.height):b.x+p.x2*b.width,y2:b.y+p.y2*b.height},'trim-s'+s.id);}
   path+=`<path data-trim-rendered="${esc(s.id)}" d="${pathData(trimStroke(s))}" fill="none" stroke="${strokePaint}" ${style}/>`;
  }
  for(const clip of s.clips??[]){
   const source=byId.get(clip.source);if(!source)continue;
   const key=JSON.stringify([clip.source,clip.rule,!!clip.inverse]);let id=clips.get(key);
   if(!id){id='vector-clip-'+clips.size;clips.set(key,id);const {d,rule}=vectorClipGeometry(v,source,clip);defs+=`<clipPath id="${id}" clipPathUnits="userSpaceOnUse" data-source="${esc(source.id)}" data-name="${esc(source.name)}" data-inverse="${!!clip.inverse}" data-source-d="${pathData(source)}" data-source-rule="${source.fillRule}"><path d="${d}" clip-rule="${rule}"/></clipPath>`;}
   path=`<g clip-path="url(#${id})">${path}</g>`;
  }
  return path;
 }).join('');
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${v.viewBox.join(' ')}" width="${v.viewBox[2]}" height="${v.viewBox[3]}"><defs>${defs}</defs>${body}</svg>`;
}

function finite(x,lo,hi,label){if(!Number.isFinite(x)||x<lo||x>hi)throw Error('Invalid vector '+label);}
function paint(p,swatches){if(typeof p==='string'){if(p!=='none'&&!/^#[\da-f]{6}$/i.test(p))throw Error('Vector paint must be a hex colour or none');}else if(p?.swatch){if(!swatches.has(p.swatch))throw Error('Missing vector swatch');}else if(p&&['linear','radial'].includes(p.type)){for(const k of ['x1','y1','x2','y2'])finite(p[k],-1e6,1e6,'gradient');if(!['objectBoundingBox','userSpaceOnUse'].includes(p.units))throw Error('Invalid gradient units');if(!Array.isArray(p.stops)||p.stops.length<2||p.stops.length>32)throw Error('Gradient needs 2–32 stops');for(const s of p.stops){finite(s.offset,0,1,'gradient stop');if(!/^#[\da-f]{6}$/i.test(s.color))throw Error('Gradient stop needs a solid colour');finite(s.opacity??1,0,1,'stop opacity');}}else throw Error('Invalid vector paint');}
export function validateVector(v){if(v===undefined)return;if(v.boil){const b=v.boil;if(typeof b.enabled!=='boolean'||!Number.isFinite(b.amount)||b.amount<0||b.amount>20||!Number.isFinite(b.rate)||b.rate<1||b.rate>30||!Number.isInteger(b.variants)||b.variants<2||b.variants>12||!Number.isFinite(b.seed)||!Number.isFinite(b.scale)||b.scale<1)throw Error('Invalid line boil settings');}if(!v||v.version!==1||!Array.isArray(v.viewBox)||v.viewBox.length!==4)throw Error('Invalid vector document');v.viewBox.forEach(x=>finite(x,-1e6,1e6,'viewBox'));if(v.viewBox[2]<=0||v.viewBox[3]<=0)throw Error('Invalid vector dimensions');finite(v.duration,.1,600,'duration');if(typeof v.loop!=='boolean')throw Error('Invalid vector loop');if(!Array.isArray(v.shapes)||v.shapes.length>5000||!Array.isArray(v.tracks)||v.tracks.length>2000||!Array.isArray(v.swatches)||v.swatches.length>256)throw Error('Vector document is too large');const ids=new Set(),swatches=new Set();for(const s of v.swatches){if(typeof s.id!=='string'||!/^[\w-]+$/.test(s.id)||typeof s.name!=='string'||s.name.length>200||!/^#[\da-f]{6}$/i.test(s.color)||swatches.has(s.id))throw Error('Duplicate vector swatch');swatches.add(s.id);paint(s.color,new Set());}let total=0;for(const s of v.shapes){if(!/^[\w-]+$/.test(s.id)||ids.has(s.id))throw Error('Invalid or duplicate vector shape');ids.add(s.id);if(typeof s.name!=='string'||s.name.length>200||s.role!==undefined&&!/^[\w-]+$/.test(s.role)||typeof s.hidden!=='boolean'||typeof s.locked!=='boolean')throw Error('Invalid vector shape metadata');if(!Array.isArray(s.commands)||!Array.isArray(s.points)||s.commands.some(c=>!['M','L','C','Z'].includes(c))||s.commands[0]!=='M'||s.commands.reduce((n,c)=>n+({M:2,L:2,C:6,Z:0}[c]),0)!==s.points.length)throw Error('Invalid vector path topology');if((total+=s.points.length)>500000)throw Error('Vector artwork is too complex');s.points.forEach(x=>finite(x,-1e6,1e6,'point'));paint(s.fill,swatches);paint(s.stroke,swatches);finite(s.opacity,0,1,'opacity');finite(s.strokeWidth,0,10000,'stroke width');if(s.trimMode!==undefined&&!['off','sequential','synced'].includes(s.trimMode))throw Error('Invalid vector trim mode');for(const channel of Object.keys(TRIM_DEFAULTS))finite(s[channel]===undefined?TRIM_DEFAULTS[channel]:s[channel],channel==='trimOffset'?-10000:0,channel==='trimOffset'?10000:1,channel);if(!['nonzero','evenodd'].includes(s.fillRule)||!['butt','round','square'].includes(s.lineCap)||!['miter','round','bevel'].includes(s.lineJoin))throw Error('Invalid vector appearance');}for(const s of v.shapes){
 if(s.clips===undefined)continue;
 if(!Array.isArray(s.clips)||s.clips.length>64)throw Error('A shape supports up to 64 clipping paths');
 const sources=new Set();
 for(const c of s.clips){if(!c||!ids.has(c.source)||c.source===s.id||sources.has(c.source))throw Error('Invalid or duplicate clipping source');if(!['nonzero','evenodd'].includes(c.rule)||c.inverse!==undefined&&typeof c.inverse!=='boolean')throw Error('Invalid clipping operation');sources.add(c.source);}
 }
 const seen=new Set();for(const t of v.tracks){if(!ids.has(t.shape)||!VECTOR_CHANNELS.includes(t.channel)||seen.has(t.shape+':'+t.channel))throw Error('Invalid vector track');seen.add(t.shape+':'+t.channel);if(!Array.isArray(t.keys)||t.keys.length>1000)throw Error('Too many vector keys');const s=v.shapes.find(s=>s.id===t.shape);let prev=-1;for(const k of t.keys){finite(k.time,0,v.duration,'key time');if(k.time<=prev)throw Error('Vector keys must be ordered');prev=k.time;if(!['linear','smooth','step','in-quad','out-quad','out-back','out-elastic','bezier'].includes(k.easing))throw Error('Invalid vector easing');validateBezier(k);if(t.channel==='points'){if(!Array.isArray(k.value)||k.value.length!==s.points.length)throw Error('Morph keys must preserve path topology');k.value.forEach(x=>finite(x,-1e6,1e6,'morph'));}else if(t.channel==='fill'||t.channel==='stroke'){if(typeof k.value!=='string')throw Error('Animated paint needs solid colours');paint(k.value,new Set());}else finite(k.value,t.channel==='trimOffset'?-10000:0,['opacity','trimStart','trimEnd'].includes(t.channel)?1:10000,'key');}}return v;}
